<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130728135312 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
			// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("CREATE TABLE achimfritz_championship_domain_model_cup (persistence_object_identifier VARCHAR(40) NOT NULL, name VARCHAR(255) NOT NULL, startdate DATETIME NOT NULL, UNIQUE INDEX flow_identity_achimfritz_championship_domain_model_cup (name), PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("CREATE TABLE achimfritz_championship_domain_model_cup_teams_join (championship_cup VARCHAR(40) NOT NULL, championship_team VARCHAR(40) NOT NULL, INDEX IDX_ACECFD7150BBF17 (championship_cup), INDEX IDX_ACECFD71E0E69356 (championship_team), PRIMARY KEY(championship_cup, championship_team)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("CREATE TABLE achimfritz_championship_domain_model_round (persistence_object_identifier VARCHAR(40) NOT NULL, cup VARCHAR(40) DEFAULT NULL, name VARCHAR(255) NOT NULL, dtype VARCHAR(255) NOT NULL, INDEX IDX_97E10FEDB79D50E4 (cup), PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("CREATE TABLE achimfritz_championship_domain_model_round_teams_join (championship_round VARCHAR(40) NOT NULL, championship_team VARCHAR(40) NOT NULL, INDEX IDX_B4C549D4CACA1535 (championship_round), INDEX IDX_B4C549D4E0E69356 (championship_team), PRIMARY KEY(championship_round, championship_team)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("CREATE TABLE achimfritz_championship_domain_model_groupround (persistence_object_identifier VARCHAR(40) NOT NULL, PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("CREATE TABLE achimfritz_championship_domain_model_grouptablerow (persistence_object_identifier VARCHAR(40) NOT NULL, team VARCHAR(40) DEFAULT NULL, groupround VARCHAR(40) DEFAULT NULL, goalsplus INT NOT NULL, goalsminus INT NOT NULL, points INT NOT NULL, rank INT NOT NULL, countofmatchesplayed INT NOT NULL, INDEX IDX_789643FC4E0A61F (team), INDEX IDX_789643FB191C15F (groupround), PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("CREATE TABLE achimfritz_championship_domain_model_koround (persistence_object_identifier VARCHAR(40) NOT NULL, parentround VARCHAR(40) DEFAULT NULL, INDEX IDX_6E295D69A528AC9B (parentround), PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("CREATE TABLE achimfritz_championship_domain_model_points (persistence_object_identifier VARCHAR(40) NOT NULL, cup VARCHAR(40) DEFAULT NULL, generalmatch VARCHAR(40) DEFAULT NULL, user VARCHAR(40) DEFAULT NULL, team VARCHAR(40) DEFAULT NULL, points INT NOT NULL, INDEX IDX_D8E7EBBCB79D50E4 (cup), INDEX IDX_D8E7EBBCDFBDA53F (generalmatch), INDEX IDX_D8E7EBBC8D93D649 (user), INDEX IDX_D8E7EBBCC4E0A61F (team), PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("CREATE TABLE achimfritz_championship_domain_model_result (persistence_object_identifier VARCHAR(40) NOT NULL, hostteamgoals INT NOT NULL, guestteamgoals INT NOT NULL, PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("CREATE TABLE achimfritz_championship_domain_model_team (persistence_object_identifier VARCHAR(40) NOT NULL, name VARCHAR(255) NOT NULL, short VARCHAR(255) NOT NULL, UNIQUE INDEX flow_identity_achimfritz_championship_domain_model_team (name), PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("CREATE TABLE achimfritz_championship_domain_model_tip (persistence_object_identifier VARCHAR(40) NOT NULL, user VARCHAR(40) DEFAULT NULL, generalmatch VARCHAR(40) DEFAULT NULL, result VARCHAR(40) DEFAULT NULL, INDEX IDX_9226C7D78D93D649 (user), INDEX IDX_9226C7D7DFBDA53F (generalmatch), UNIQUE INDEX UNIQ_9226C7D7136AC113 (result), PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("CREATE TABLE achimfritz_championship_domain_model_user (persistence_object_identifier VARCHAR(40) NOT NULL, name VARCHAR(255) NOT NULL, UNIQUE INDEX flow_identity_achimfritz_championship_domain_model_user (name), PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("CREATE TABLE achimfritz_championship_domain_model_match (persistence_object_identifier VARCHAR(40) NOT NULL, hostteam VARCHAR(40) DEFAULT NULL, guestteam VARCHAR(40) DEFAULT NULL, cup VARCHAR(40) DEFAULT NULL, round VARCHAR(40) DEFAULT NULL, result VARCHAR(40) DEFAULT NULL, startdate DATETIME NOT NULL, name VARCHAR(255) NOT NULL, dtype VARCHAR(255) NOT NULL, INDEX IDX_285420DC7F921808 (hostteam), INDEX IDX_285420DC87754416 (guestteam), INDEX IDX_285420DCB79D50E4 (cup), INDEX IDX_285420DCC5EEEA34 (round), UNIQUE INDEX UNIQ_285420DC136AC113 (result), PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("CREATE TABLE achimfritz_championship_domain_model_komatch (persistence_object_identifier VARCHAR(40) NOT NULL, PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("CREATE TABLE achimfritz_championship_domain_model_crossgrouproundmatch (persistence_object_identifier VARCHAR(40) NOT NULL, winnerofgroupround VARCHAR(40) DEFAULT NULL, semiwinnerofgroupround VARCHAR(40) DEFAULT NULL, INDEX IDX_415239FA89EA8AA8 (winnerofgroupround), INDEX IDX_415239FA5616BC5D (semiwinnerofgroupround), PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("CREATE TABLE achimfritz_championship_domain_model_groupmatch (persistence_object_identifier VARCHAR(40) NOT NULL, PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("CREATE TABLE achimfritz_championship_domain_model_winnersoftwomatchesmatch (persistence_object_identifier VARCHAR(40) NOT NULL, hostmatch VARCHAR(40) DEFAULT NULL, guestmatch VARCHAR(40) DEFAULT NULL, UNIQUE INDEX UNIQ_26E95E79F933327C (hostmatch), UNIQUE INDEX UNIQ_26E95E793C4E843 (guestmatch), PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_cup_teams_join ADD CONSTRAINT FK_ACECFD7150BBF17 FOREIGN KEY (championship_cup) REFERENCES achimfritz_championship_domain_model_cup (persistence_object_identifier)");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_cup_teams_join ADD CONSTRAINT FK_ACECFD71E0E69356 FOREIGN KEY (championship_team) REFERENCES achimfritz_championship_domain_model_team (persistence_object_identifier)");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_round ADD CONSTRAINT FK_97E10FEDB79D50E4 FOREIGN KEY (cup) REFERENCES achimfritz_championship_domain_model_cup (persistence_object_identifier)");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_round_teams_join ADD CONSTRAINT FK_B4C549D4CACA1535 FOREIGN KEY (championship_round) REFERENCES achimfritz_championship_domain_model_round (persistence_object_identifier)");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_round_teams_join ADD CONSTRAINT FK_B4C549D4E0E69356 FOREIGN KEY (championship_team) REFERENCES achimfritz_championship_domain_model_team (persistence_object_identifier)");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_groupround ADD CONSTRAINT FK_5704159647A46B0A FOREIGN KEY (persistence_object_identifier) REFERENCES achimfritz_championship_domain_model_round (persistence_object_identifier) ON DELETE CASCADE");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_grouptablerow ADD CONSTRAINT FK_789643FC4E0A61F FOREIGN KEY (team) REFERENCES achimfritz_championship_domain_model_team (persistence_object_identifier)");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_grouptablerow ADD CONSTRAINT FK_789643FB191C15F FOREIGN KEY (groupround) REFERENCES achimfritz_championship_domain_model_groupround (persistence_object_identifier)");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_koround ADD CONSTRAINT FK_6E295D69A528AC9B FOREIGN KEY (parentround) REFERENCES achimfritz_championship_domain_model_koround (persistence_object_identifier)");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_koround ADD CONSTRAINT FK_6E295D6947A46B0A FOREIGN KEY (persistence_object_identifier) REFERENCES achimfritz_championship_domain_model_round (persistence_object_identifier) ON DELETE CASCADE");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_points ADD CONSTRAINT FK_D8E7EBBCB79D50E4 FOREIGN KEY (cup) REFERENCES achimfritz_championship_domain_model_cup (persistence_object_identifier)");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_points ADD CONSTRAINT FK_D8E7EBBCDFBDA53F FOREIGN KEY (generalmatch) REFERENCES achimfritz_championship_domain_model_match (persistence_object_identifier)");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_points ADD CONSTRAINT FK_D8E7EBBC8D93D649 FOREIGN KEY (user) REFERENCES achimfritz_championship_domain_model_user (persistence_object_identifier)");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_points ADD CONSTRAINT FK_D8E7EBBCC4E0A61F FOREIGN KEY (team) REFERENCES achimfritz_championship_domain_model_team (persistence_object_identifier)");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_tip ADD CONSTRAINT FK_9226C7D78D93D649 FOREIGN KEY (user) REFERENCES achimfritz_championship_domain_model_user (persistence_object_identifier)");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_tip ADD CONSTRAINT FK_9226C7D7DFBDA53F FOREIGN KEY (generalmatch) REFERENCES achimfritz_championship_domain_model_match (persistence_object_identifier)");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_tip ADD CONSTRAINT FK_9226C7D7136AC113 FOREIGN KEY (result) REFERENCES achimfritz_championship_domain_model_result (persistence_object_identifier)");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_match ADD CONSTRAINT FK_285420DC7F921808 FOREIGN KEY (hostteam) REFERENCES achimfritz_championship_domain_model_team (persistence_object_identifier)");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_match ADD CONSTRAINT FK_285420DC87754416 FOREIGN KEY (guestteam) REFERENCES achimfritz_championship_domain_model_team (persistence_object_identifier)");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_match ADD CONSTRAINT FK_285420DCB79D50E4 FOREIGN KEY (cup) REFERENCES achimfritz_championship_domain_model_cup (persistence_object_identifier)");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_match ADD CONSTRAINT FK_285420DCC5EEEA34 FOREIGN KEY (round) REFERENCES achimfritz_championship_domain_model_round (persistence_object_identifier)");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_match ADD CONSTRAINT FK_285420DC136AC113 FOREIGN KEY (result) REFERENCES achimfritz_championship_domain_model_result (persistence_object_identifier)");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_komatch ADD CONSTRAINT FK_D19C725847A46B0A FOREIGN KEY (persistence_object_identifier) REFERENCES achimfritz_championship_domain_model_match (persistence_object_identifier) ON DELETE CASCADE");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_crossgrouproundmatch ADD CONSTRAINT FK_415239FA89EA8AA8 FOREIGN KEY (winnerofgroupround) REFERENCES achimfritz_championship_domain_model_groupround (persistence_object_identifier)");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_crossgrouproundmatch ADD CONSTRAINT FK_415239FA5616BC5D FOREIGN KEY (semiwinnerofgroupround) REFERENCES achimfritz_championship_domain_model_groupround (persistence_object_identifier)");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_crossgrouproundmatch ADD CONSTRAINT FK_415239FA47A46B0A FOREIGN KEY (persistence_object_identifier) REFERENCES achimfritz_championship_domain_model_match (persistence_object_identifier) ON DELETE CASCADE");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_groupmatch ADD CONSTRAINT FK_E8B13AA747A46B0A FOREIGN KEY (persistence_object_identifier) REFERENCES achimfritz_championship_domain_model_match (persistence_object_identifier) ON DELETE CASCADE");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_winnersoftwomatchesmatch ADD CONSTRAINT FK_26E95E79F933327C FOREIGN KEY (hostmatch) REFERENCES achimfritz_championship_domain_model_komatch (persistence_object_identifier)");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_winnersoftwomatchesmatch ADD CONSTRAINT FK_26E95E793C4E843 FOREIGN KEY (guestmatch) REFERENCES achimfritz_championship_domain_model_komatch (persistence_object_identifier)");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_winnersoftwomatchesmatch ADD CONSTRAINT FK_26E95E7947A46B0A FOREIGN KEY (persistence_object_identifier) REFERENCES achimfritz_championship_domain_model_match (persistence_object_identifier) ON DELETE CASCADE");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
			// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_cup_teams_join DROP FOREIGN KEY FK_ACECFD7150BBF17");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_round DROP FOREIGN KEY FK_97E10FEDB79D50E4");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_points DROP FOREIGN KEY FK_D8E7EBBCB79D50E4");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_match DROP FOREIGN KEY FK_285420DCB79D50E4");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_round_teams_join DROP FOREIGN KEY FK_B4C549D4CACA1535");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_groupround DROP FOREIGN KEY FK_5704159647A46B0A");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_koround DROP FOREIGN KEY FK_6E295D6947A46B0A");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_match DROP FOREIGN KEY FK_285420DCC5EEEA34");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_grouptablerow DROP FOREIGN KEY FK_789643FB191C15F");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_crossgrouproundmatch DROP FOREIGN KEY FK_415239FA89EA8AA8");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_crossgrouproundmatch DROP FOREIGN KEY FK_415239FA5616BC5D");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_koround DROP FOREIGN KEY FK_6E295D69A528AC9B");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_tip DROP FOREIGN KEY FK_9226C7D7136AC113");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_match DROP FOREIGN KEY FK_285420DC136AC113");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_cup_teams_join DROP FOREIGN KEY FK_ACECFD71E0E69356");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_round_teams_join DROP FOREIGN KEY FK_B4C549D4E0E69356");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_grouptablerow DROP FOREIGN KEY FK_789643FC4E0A61F");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_points DROP FOREIGN KEY FK_D8E7EBBCC4E0A61F");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_match DROP FOREIGN KEY FK_285420DC7F921808");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_match DROP FOREIGN KEY FK_285420DC87754416");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_points DROP FOREIGN KEY FK_D8E7EBBC8D93D649");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_tip DROP FOREIGN KEY FK_9226C7D78D93D649");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_points DROP FOREIGN KEY FK_D8E7EBBCDFBDA53F");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_tip DROP FOREIGN KEY FK_9226C7D7DFBDA53F");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_komatch DROP FOREIGN KEY FK_D19C725847A46B0A");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_crossgrouproundmatch DROP FOREIGN KEY FK_415239FA47A46B0A");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_groupmatch DROP FOREIGN KEY FK_E8B13AA747A46B0A");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_winnersoftwomatchesmatch DROP FOREIGN KEY FK_26E95E7947A46B0A");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_winnersoftwomatchesmatch DROP FOREIGN KEY FK_26E95E79F933327C");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_winnersoftwomatchesmatch DROP FOREIGN KEY FK_26E95E793C4E843");
		$this->addSql("DROP TABLE achimfritz_championship_domain_model_cup");
		$this->addSql("DROP TABLE achimfritz_championship_domain_model_cup_teams_join");
		$this->addSql("DROP TABLE achimfritz_championship_domain_model_round");
		$this->addSql("DROP TABLE achimfritz_championship_domain_model_round_teams_join");
		$this->addSql("DROP TABLE achimfritz_championship_domain_model_groupround");
		$this->addSql("DROP TABLE achimfritz_championship_domain_model_grouptablerow");
		$this->addSql("DROP TABLE achimfritz_championship_domain_model_koround");
		$this->addSql("DROP TABLE achimfritz_championship_domain_model_points");
		$this->addSql("DROP TABLE achimfritz_championship_domain_model_result");
		$this->addSql("DROP TABLE achimfritz_championship_domain_model_team");
		$this->addSql("DROP TABLE achimfritz_championship_domain_model_tip");
		$this->addSql("DROP TABLE achimfritz_championship_domain_model_user");
		$this->addSql("DROP TABLE achimfritz_championship_domain_model_match");
		$this->addSql("DROP TABLE achimfritz_championship_domain_model_komatch");
		$this->addSql("DROP TABLE achimfritz_championship_domain_model_crossgrouproundmatch");
		$this->addSql("DROP TABLE achimfritz_championship_domain_model_groupmatch");
		$this->addSql("DROP TABLE achimfritz_championship_domain_model_winnersoftwomatchesmatch");
	}
}

?>