<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130910185010 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
			// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_match DROP FOREIGN KEY FK_285420DC1C47C160");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_match DROP FOREIGN KEY FK_285420DC89CCCBF8");
		$this->addSql("CREATE TABLE achimfritz_championship_domain_model_childkoround (persistence_object_identifier VARCHAR(40) NOT NULL, parentround VARCHAR(40) DEFAULT NULL, INDEX IDX_E553D847A528AC9B (parentround), PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("CREATE TABLE achimfritz_championship_domain_model_crossgrouproundmatch (persistence_object_identifier VARCHAR(40) NOT NULL, hostgroupround VARCHAR(40) DEFAULT NULL, guestgroupround VARCHAR(40) DEFAULT NULL, hostgrouprank INT NOT NULL, guestgrouprank INT NOT NULL, INDEX IDX_415239FA8883CEF (hostgroupround), INDEX IDX_415239FA3CC82627 (guestgroupround), PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("CREATE TABLE achimfritz_championship_domain_model_teamsoftwomatchesmatch (persistence_object_identifier VARCHAR(40) NOT NULL, hostmatch VARCHAR(40) DEFAULT NULL, guestmatch VARCHAR(40) DEFAULT NULL, hostmatchiswinner TINYINT(1) NOT NULL, guestmatchiswinner TINYINT(1) NOT NULL, UNIQUE INDEX UNIQ_7BB97C90F933327C (hostmatch), UNIQUE INDEX UNIQ_7BB97C903C4E843 (guestmatch), PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_childkoround ADD CONSTRAINT FK_E553D847A528AC9B FOREIGN KEY (parentround) REFERENCES achimfritz_championship_domain_model_koround (persistence_object_identifier)");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_childkoround ADD CONSTRAINT FK_E553D84747A46B0A FOREIGN KEY (persistence_object_identifier) REFERENCES achimfritz_championship_domain_model_round (persistence_object_identifier) ON DELETE CASCADE");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_crossgrouproundmatch ADD CONSTRAINT FK_415239FA8883CEF FOREIGN KEY (hostgroupround) REFERENCES achimfritz_championship_domain_model_groupround (persistence_object_identifier)");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_crossgrouproundmatch ADD CONSTRAINT FK_415239FA3CC82627 FOREIGN KEY (guestgroupround) REFERENCES achimfritz_championship_domain_model_groupround (persistence_object_identifier)");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_crossgrouproundmatch ADD CONSTRAINT FK_415239FA47A46B0A FOREIGN KEY (persistence_object_identifier) REFERENCES achimfritz_championship_domain_model_match (persistence_object_identifier) ON DELETE CASCADE");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_teamsoftwomatchesmatch ADD CONSTRAINT FK_7BB97C90F933327C FOREIGN KEY (hostmatch) REFERENCES achimfritz_championship_domain_model_komatch (persistence_object_identifier)");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_teamsoftwomatchesmatch ADD CONSTRAINT FK_7BB97C903C4E843 FOREIGN KEY (guestmatch) REFERENCES achimfritz_championship_domain_model_komatch (persistence_object_identifier)");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_teamsoftwomatchesmatch ADD CONSTRAINT FK_7BB97C9047A46B0A FOREIGN KEY (persistence_object_identifier) REFERENCES achimfritz_championship_domain_model_match (persistence_object_identifier) ON DELETE CASCADE");
		$this->addSql("DROP TABLE achimfritz_championship_domain_model_finalround");
		$this->addSql("DROP TABLE achimfritz_championship_domain_model_matchparticipant");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_koround DROP FOREIGN KEY FK_6E295D69A528AC9B");
		$this->addSql("DROP INDEX IDX_6E295D69A528AC9B ON achimfritz_championship_domain_model_koround");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_koround DROP parentround");
		$this->addSql("DROP INDEX UNIQ_285420DC1C47C160 ON achimfritz_championship_domain_model_match");
		$this->addSql("DROP INDEX UNIQ_285420DC89CCCBF8 ON achimfritz_championship_domain_model_match");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_match ADD hostteam VARCHAR(40) DEFAULT NULL, ADD guestteam VARCHAR(40) DEFAULT NULL, DROP hostparticipant, DROP guestparticipant");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_match ADD CONSTRAINT FK_285420DC7F921808 FOREIGN KEY (hostteam) REFERENCES achimfritz_championship_domain_model_team (persistence_object_identifier)");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_match ADD CONSTRAINT FK_285420DC87754416 FOREIGN KEY (guestteam) REFERENCES achimfritz_championship_domain_model_team (persistence_object_identifier)");
		$this->addSql("CREATE INDEX IDX_285420DC7F921808 ON achimfritz_championship_domain_model_match (hostteam)");
		$this->addSql("CREATE INDEX IDX_285420DC87754416 ON achimfritz_championship_domain_model_match (guestteam)");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
			// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("CREATE TABLE achimfritz_championship_domain_model_finalround (persistence_object_identifier VARCHAR(40) NOT NULL, PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("CREATE TABLE achimfritz_championship_domain_model_matchparticipant (persistence_object_identifier VARCHAR(40) NOT NULL, winnerofmatch VARCHAR(40) DEFAULT NULL, groupround VARCHAR(40) DEFAULT NULL, team VARCHAR(40) DEFAULT NULL, looserofmatch VARCHAR(40) DEFAULT NULL, rankofgroupround INT NOT NULL, UNIQUE INDEX UNIQ_98AA7B24572F536F (winnerofmatch), UNIQUE INDEX UNIQ_98AA7B24F8023A6E (looserofmatch), INDEX IDX_98AA7B24C4E0A61F (team), INDEX IDX_98AA7B24B191C15F (groupround), PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_finalround ADD CONSTRAINT FK_BD7CD8A747A46B0A FOREIGN KEY (persistence_object_identifier) REFERENCES achimfritz_championship_domain_model_round (persistence_object_identifier) ON DELETE CASCADE");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_matchparticipant ADD CONSTRAINT FK_98AA7B24572F536F FOREIGN KEY (winnerofmatch) REFERENCES achimfritz_championship_domain_model_match (persistence_object_identifier)");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_matchparticipant ADD CONSTRAINT FK_98AA7B24B191C15F FOREIGN KEY (groupround) REFERENCES achimfritz_championship_domain_model_groupround (persistence_object_identifier)");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_matchparticipant ADD CONSTRAINT FK_98AA7B24C4E0A61F FOREIGN KEY (team) REFERENCES achimfritz_championship_domain_model_team (persistence_object_identifier)");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_matchparticipant ADD CONSTRAINT FK_98AA7B24F8023A6E FOREIGN KEY (looserofmatch) REFERENCES achimfritz_championship_domain_model_match (persistence_object_identifier)");
		$this->addSql("DROP TABLE achimfritz_championship_domain_model_childkoround");
		$this->addSql("DROP TABLE achimfritz_championship_domain_model_crossgrouproundmatch");
		$this->addSql("DROP TABLE achimfritz_championship_domain_model_teamsoftwomatchesmatch");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_koround ADD parentround VARCHAR(40) DEFAULT NULL");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_koround ADD CONSTRAINT FK_6E295D69A528AC9B FOREIGN KEY (parentround) REFERENCES achimfritz_championship_domain_model_koround (persistence_object_identifier)");
		$this->addSql("CREATE INDEX IDX_6E295D69A528AC9B ON achimfritz_championship_domain_model_koround (parentround)");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_match DROP FOREIGN KEY FK_285420DC7F921808");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_match DROP FOREIGN KEY FK_285420DC87754416");
		$this->addSql("DROP INDEX IDX_285420DC7F921808 ON achimfritz_championship_domain_model_match");
		$this->addSql("DROP INDEX IDX_285420DC87754416 ON achimfritz_championship_domain_model_match");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_match ADD hostparticipant VARCHAR(40) DEFAULT NULL, ADD guestparticipant VARCHAR(40) DEFAULT NULL, DROP hostteam, DROP guestteam");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_match ADD CONSTRAINT FK_285420DC1C47C160 FOREIGN KEY (hostparticipant) REFERENCES achimfritz_championship_domain_model_matchparticipant (persistence_object_identifier)");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_match ADD CONSTRAINT FK_285420DC89CCCBF8 FOREIGN KEY (guestparticipant) REFERENCES achimfritz_championship_domain_model_matchparticipant (persistence_object_identifier)");
		$this->addSql("CREATE UNIQUE INDEX UNIQ_285420DC1C47C160 ON achimfritz_championship_domain_model_match (hostparticipant)");
		$this->addSql("CREATE UNIQUE INDEX UNIQ_285420DC89CCCBF8 ON achimfritz_championship_domain_model_match (guestparticipant)");
	}
}

?>