<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130601175353 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
			// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("DROP TABLE achimfritz_championship_domain_model_matchparticipant_team_join");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_matchparticipant DROP INDEX UNIQ_98AA7B24B191C15F, ADD INDEX IDX_98AA7B24B191C15F (groupround)");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_matchparticipant ADD team VARCHAR(40) DEFAULT NULL");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_matchparticipant ADD CONSTRAINT FK_98AA7B24C4E0A61F FOREIGN KEY (team) REFERENCES achimfritz_championship_domain_model_team (persistence_object_identifier)");
		$this->addSql("CREATE INDEX IDX_98AA7B24C4E0A61F ON achimfritz_championship_domain_model_matchparticipant (team)");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
			// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("CREATE TABLE achimfritz_championship_domain_model_matchparticipant_team_join (championship_matchparticipant VARCHAR(40) NOT NULL, championship_team VARCHAR(40) NOT NULL, INDEX IDX_67F6B00CD33D9992 (championship_matchparticipant), INDEX IDX_67F6B00CE0E69356 (championship_team), PRIMARY KEY(championship_matchparticipant, championship_team)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_matchparticipant_team_join ADD CONSTRAINT FK_67F6B00CD33D9992 FOREIGN KEY (championship_matchparticipant) REFERENCES achimfritz_championship_domain_model_matchparticipant (persistence_object_identifier)");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_matchparticipant_team_join ADD CONSTRAINT FK_67F6B00CE0E69356 FOREIGN KEY (championship_team) REFERENCES achimfritz_championship_domain_model_team (persistence_object_identifier)");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_matchparticipant DROP INDEX IDX_98AA7B24B191C15F, ADD UNIQUE INDEX UNIQ_98AA7B24B191C15F (groupround)");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_matchparticipant DROP FOREIGN KEY FK_98AA7B24C4E0A61F");
		$this->addSql("DROP INDEX IDX_98AA7B24C4E0A61F ON achimfritz_championship_domain_model_matchparticipant");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_matchparticipant DROP team");
	}
}

?>