<?php
namespace Neos\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20160410180752 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
		// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("ALTER TABLE achimfritz_championship_chat_domain_model_chatentry DROP FOREIGN KEY FK_2610B8658D93D649");
		$this->addSql("DROP INDEX idx_2610b8658d93d649 ON achimfritz_championship_chat_domain_model_chatentry");
		$this->addSql("CREATE INDEX IDX_14B43D818D93D649 ON achimfritz_championship_chat_domain_model_chatentry (user)");
		$this->addSql("ALTER TABLE achimfritz_championship_chat_domain_model_chatentry ADD CONSTRAINT FK_2610B8658D93D649 FOREIGN KEY (user) REFERENCES achimfritz_championship_user_domain_model_user (persistence_object_identifier)");
		$this->addSql("ALTER TABLE achimfritz_championship_chat_domain_model_tipgroupchatentry DROP FOREIGN KEY FK_203E73E3F3D6F72C");
		$this->addSql("DROP INDEX idx_203e73e3f3d6f72c ON achimfritz_championship_chat_domain_model_tipgroupchatentry");
		$this->addSql("CREATE INDEX IDX_A4E62533F3D6F72C ON achimfritz_championship_chat_domain_model_tipgroupchatentry (tipgroup)");
		$this->addSql("ALTER TABLE achimfritz_championship_chat_domain_model_tipgroupchatentry ADD CONSTRAINT FK_203E73E3F3D6F72C FOREIGN KEY (tipgroup) REFERENCES achimfritz_championship_tip_domain_model_tipgroup (persistence_object_identifier)");
		$this->addSql("ALTER TABLE achimfritz_championship_tip_domain_model_ranking DROP FOREIGN KEY FK_22037E8D93D649");
		$this->addSql("DROP INDEX idx_22037e8d93d649 ON achimfritz_championship_tip_domain_model_ranking");
		$this->addSql("CREATE INDEX IDX_B5BAA8C78D93D649 ON achimfritz_championship_tip_domain_model_ranking (user)");
		$this->addSql("ALTER TABLE achimfritz_championship_tip_domain_model_ranking ADD CONSTRAINT FK_22037E8D93D649 FOREIGN KEY (user) REFERENCES achimfritz_championship_user_domain_model_user (persistence_object_identifier)");
		$this->addSql("ALTER TABLE achimfritz_championship_tip_domain_model_tip DROP FOREIGN KEY FK_9226C7D7136AC113");
		$this->addSql("ALTER TABLE achimfritz_championship_tip_domain_model_tip DROP FOREIGN KEY FK_9226C7D78D93D649");
		$this->addSql("ALTER TABLE achimfritz_championship_tip_domain_model_tip DROP FOREIGN KEY FK_9226C7D7DFBDA53F");
		$this->addSql("DROP INDEX idx_9226c7d78d93d649 ON achimfritz_championship_tip_domain_model_tip");
		$this->addSql("CREATE INDEX IDX_1ADA9F058D93D649 ON achimfritz_championship_tip_domain_model_tip (user)");
		$this->addSql("DROP INDEX idx_9226c7d7dfbda53f ON achimfritz_championship_tip_domain_model_tip");
		$this->addSql("CREATE INDEX IDX_1ADA9F05DFBDA53F ON achimfritz_championship_tip_domain_model_tip (generalmatch)");
		$this->addSql("DROP INDEX uniq_9226c7d7136ac113 ON achimfritz_championship_tip_domain_model_tip");
		$this->addSql("CREATE UNIQUE INDEX UNIQ_1ADA9F05136AC113 ON achimfritz_championship_tip_domain_model_tip (result)");
		$this->addSql("ALTER TABLE achimfritz_championship_tip_domain_model_tip ADD CONSTRAINT FK_9226C7D7136AC113 FOREIGN KEY (result) REFERENCES achimfritz_championship_competition_domain_model_result (persistence_object_identifier)");
		$this->addSql("ALTER TABLE achimfritz_championship_tip_domain_model_tip ADD CONSTRAINT FK_9226C7D78D93D649 FOREIGN KEY (user) REFERENCES achimfritz_championship_user_domain_model_user (persistence_object_identifier)");
		$this->addSql("ALTER TABLE achimfritz_championship_tip_domain_model_tip ADD CONSTRAINT FK_9226C7D7DFBDA53F FOREIGN KEY (generalmatch) REFERENCES achimfritz_championship_competition_domain_model_match (persistence_object_identifier)");
		$this->addSql("DROP INDEX flow_identity_achimfritz_championship_domain_model_tipgroup ON achimfritz_championship_tip_domain_model_tipgroup");
		$this->addSql("CREATE UNIQUE INDEX flow_identity_achimfritz_championship_tip_domain_model_tipgroup ON achimfritz_championship_tip_domain_model_tipgroup (name)");
		$this->addSql("ALTER TABLE achimfritz_championship_tip_domain_model_tipgr_c2a81_users_join DROP FOREIGN KEY FK_6F435DBC246893B3");
		$this->addSql("ALTER TABLE achimfritz_championship_tip_domain_model_tipgr_c2a81_users_join DROP FOREIGN KEY FK_6F435DBCA995E300");
		$this->addSql("DROP INDEX idx_6f435dbc246893b3 ON achimfritz_championship_tip_domain_model_tipgr_c2a81_users_join");
		$this->addSql("CREATE INDEX IDX_7B25C34045E83D34 ON achimfritz_championship_tip_domain_model_tipgr_c2a81_users_join (tip_tipgroupresultmatrix)");
		$this->addSql("DROP INDEX idx_6f435dbca995e300 ON achimfritz_championship_tip_domain_model_tipgr_c2a81_users_join");
		$this->addSql("CREATE INDEX IDX_7B25C340F7129A80 ON achimfritz_championship_tip_domain_model_tipgr_c2a81_users_join (user_user)");
		$this->addSql("ALTER TABLE achimfritz_championship_tip_domain_model_tipgr_c2a81_users_join ADD CONSTRAINT FK_6F435DBC246893B3 FOREIGN KEY (tip_tipgroupresultmatrix) REFERENCES achimfritz_championship_tip_domain_model_tipgroupresultmatrix (persistence_object_identifier)");
		$this->addSql("ALTER TABLE achimfritz_championship_tip_domain_model_tipgr_c2a81_users_join ADD CONSTRAINT FK_6F435DBCA995E300 FOREIGN KEY (user_user) REFERENCES achimfritz_championship_user_domain_model_user (persistence_object_identifier)");
		$this->addSql("ALTER TABLE achimfritz_championship_tip_domain_model_tipgro_c2a81_rows_join DROP FOREIGN KEY FK_A8E08DB6246893B3");
		$this->addSql("ALTER TABLE achimfritz_championship_tip_domain_model_tipgro_c2a81_rows_join DROP FOREIGN KEY FK_A8E08DB65A2D8605");
		$this->addSql("DROP INDEX idx_a8e08db6246893b3 ON achimfritz_championship_tip_domain_model_tipgro_c2a81_rows_join");
		$this->addSql("CREATE INDEX IDX_E50D217345E83D34 ON achimfritz_championship_tip_domain_model_tipgro_c2a81_rows_join (tip_tipgroupresultmatrix)");
		$this->addSql("DROP INDEX idx_a8e08db65a2d8605 ON achimfritz_championship_tip_domain_model_tipgro_c2a81_rows_join");
		$this->addSql("CREATE INDEX IDX_E50D2173636B9926 ON achimfritz_championship_tip_domain_model_tipgro_c2a81_rows_join (tip_tipgroupresultmatrixrow)");
		$this->addSql("ALTER TABLE achimfritz_championship_tip_domain_model_tipgro_c2a81_rows_join ADD CONSTRAINT FK_A8E08DB6246893B3 FOREIGN KEY (tip_tipgroupresultmatrix) REFERENCES achimfritz_championship_tip_domain_model_tipgroupresultmatrix (persistence_object_identifier)");
		$this->addSql("ALTER TABLE achimfritz_championship_tip_domain_model_tipgro_c2a81_rows_join ADD CONSTRAINT FK_A8E08DB65A2D8605 FOREIGN KEY (tip_tipgroupresultmatrixrow) REFERENCES achimfritz_championship_tip_domain_model_tipgroupresultma_d24a5 (persistence_object_identifier)");
		$this->addSql("ALTER TABLE achimfritz_championship_tip_domain_model_tipgroupresultma_d24a5 DROP FOREIGN KEY FK_6D37622ADFBDA53F");
		$this->addSql("DROP INDEX uniq_6d37622adfbda53f ON achimfritz_championship_tip_domain_model_tipgroupresultma_d24a5");
		$this->addSql("CREATE UNIQUE INDEX UNIQ_BFA4B76ADFBDA53F ON achimfritz_championship_tip_domain_model_tipgroupresultma_d24a5 (generalmatch)");
		$this->addSql("ALTER TABLE achimfritz_championship_tip_domain_model_tipgroupresultma_d24a5 ADD CONSTRAINT FK_6D37622ADFBDA53F FOREIGN KEY (generalmatch) REFERENCES achimfritz_championship_competition_domain_model_match (persistence_object_identifier)");
		$this->addSql("ALTER TABLE achimfritz_championship_tip_domain_model_tipgro_d24a5_tips_join DROP FOREIGN KEY FK_52665F765A2D8605");
		$this->addSql("ALTER TABLE achimfritz_championship_tip_domain_model_tipgro_d24a5_tips_join DROP FOREIGN KEY FK_52665F76FA1557BF");
		$this->addSql("DROP INDEX idx_52665f765a2d8605 ON achimfritz_championship_tip_domain_model_tipgro_d24a5_tips_join");
		$this->addSql("CREATE INDEX IDX_B70F797636B9926 ON achimfritz_championship_tip_domain_model_tipgro_d24a5_tips_join (tip_tipgroupresultmatrixrow)");
		$this->addSql("DROP INDEX idx_52665f76fa1557bf ON achimfritz_championship_tip_domain_model_tipgro_d24a5_tips_join");
		$this->addSql("CREATE INDEX IDX_B70F79777CEEBB1 ON achimfritz_championship_tip_domain_model_tipgro_d24a5_tips_join (tip_tip)");
		$this->addSql("ALTER TABLE achimfritz_championship_tip_domain_model_tipgro_d24a5_tips_join ADD CONSTRAINT FK_52665F765A2D8605 FOREIGN KEY (tip_tipgroupresultmatrixrow) REFERENCES achimfritz_championship_tip_domain_model_tipgroupresultma_d24a5 (persistence_object_identifier)");
		$this->addSql("ALTER TABLE achimfritz_championship_tip_domain_model_tipgro_d24a5_tips_join ADD CONSTRAINT FK_52665F76FA1557BF FOREIGN KEY (tip_tip) REFERENCES achimfritz_championship_tip_domain_model_tip (persistence_object_identifier)");
		$this->addSql("ALTER TABLE achimfritz_championship_user_domain_model_password DROP FOREIGN KEY FK_42C52008D93D649");
		$this->addSql("DROP INDEX uniq_42c52008d93d649 ON achimfritz_championship_user_domain_model_password");
		$this->addSql("CREATE UNIQUE INDEX UNIQ_28743D4A8D93D649 ON achimfritz_championship_user_domain_model_password (user)");
		$this->addSql("ALTER TABLE achimfritz_championship_user_domain_model_password ADD CONSTRAINT FK_42C52008D93D649 FOREIGN KEY (user) REFERENCES achimfritz_championship_user_domain_model_user (persistence_object_identifier)");
		$this->addSql("ALTER TABLE achimfritz_championship_user_domain_model_user DROP FOREIGN KEY FK_EA9439FA7D3656A4");
		$this->addSql("ALTER TABLE achimfritz_championship_user_domain_model_user DROP FOREIGN KEY FK_EA9439FAF3D6F72C");
		$this->addSql("DROP INDEX uniq_ea9439fa7d3656a4 ON achimfritz_championship_user_domain_model_user");
		$this->addSql("CREATE UNIQUE INDEX UNIQ_62FB7B77D3656A4 ON achimfritz_championship_user_domain_model_user (account)");
		$this->addSql("DROP INDEX idx_ea9439faf3d6f72c ON achimfritz_championship_user_domain_model_user");
		$this->addSql("CREATE INDEX IDX_62FB7B7F3D6F72C ON achimfritz_championship_user_domain_model_user (tipgroup)");
		$this->addSql("ALTER TABLE achimfritz_championship_user_domain_model_user ADD CONSTRAINT FK_EA9439FA7D3656A4 FOREIGN KEY (account) REFERENCES typo3_flow_security_account (persistence_object_identifier)");
		$this->addSql("ALTER TABLE achimfritz_championship_user_domain_model_user ADD CONSTRAINT FK_EA9439FAF3D6F72C FOREIGN KEY (tipgroup) REFERENCES achimfritz_championship_tip_domain_model_tipgroup (persistence_object_identifier)");
		$this->addSql("ALTER TABLE achimfritz_championship_user_domain_model_user_tipgroups_join DROP FOREIGN KEY FK_318E50795D3384B7");
		$this->addSql("ALTER TABLE achimfritz_championship_user_domain_model_user_tipgroups_join DROP FOREIGN KEY FK_318E5079A995E300");
		$this->addSql("DROP INDEX idx_318e5079a995e300 ON achimfritz_championship_user_domain_model_user_tipgroups_join");
		$this->addSql("CREATE INDEX IDX_42D6DA98F7129A80 ON achimfritz_championship_user_domain_model_user_tipgroups_join (user_user)");
		$this->addSql("DROP INDEX idx_318e50795d3384b7 ON achimfritz_championship_user_domain_model_user_tipgroups_join");
		$this->addSql("CREATE INDEX IDX_42D6DA98BA56F723 ON achimfritz_championship_user_domain_model_user_tipgroups_join (tip_tipgroup)");
		$this->addSql("ALTER TABLE achimfritz_championship_user_domain_model_user_tipgroups_join ADD CONSTRAINT FK_318E50795D3384B7 FOREIGN KEY (tip_tipgroup) REFERENCES achimfritz_championship_tip_domain_model_tipgroup (persistence_object_identifier)");
		$this->addSql("ALTER TABLE achimfritz_championship_user_domain_model_user_tipgroups_join ADD CONSTRAINT FK_318E5079A995E300 FOREIGN KEY (user_user) REFERENCES achimfritz_championship_user_domain_model_user (persistence_object_identifier)");
		$this->addSql("ALTER TABLE typo3_flow_security_account CHANGE failedauthenticationcount failedauthenticationcount INT DEFAULT NULL");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
		// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("ALTER TABLE achimfritz_championship_chat_domain_model_chatentry DROP FOREIGN KEY FK_14B43D818D93D649");
		$this->addSql("DROP INDEX idx_14b43d818d93d649 ON achimfritz_championship_chat_domain_model_chatentry");
		$this->addSql("CREATE INDEX IDX_2610B8658D93D649 ON achimfritz_championship_chat_domain_model_chatentry (user)");
		$this->addSql("ALTER TABLE achimfritz_championship_chat_domain_model_chatentry ADD CONSTRAINT FK_14B43D818D93D649 FOREIGN KEY (user) REFERENCES achimfritz_championship_user_domain_model_user (persistence_object_identifier)");
		$this->addSql("ALTER TABLE achimfritz_championship_chat_domain_model_tipgroupchatentry DROP FOREIGN KEY FK_A4E62533F3D6F72C");
		$this->addSql("DROP INDEX idx_a4e62533f3d6f72c ON achimfritz_championship_chat_domain_model_tipgroupchatentry");
		$this->addSql("CREATE INDEX IDX_203E73E3F3D6F72C ON achimfritz_championship_chat_domain_model_tipgroupchatentry (tipgroup)");
		$this->addSql("ALTER TABLE achimfritz_championship_chat_domain_model_tipgroupchatentry ADD CONSTRAINT FK_A4E62533F3D6F72C FOREIGN KEY (tipgroup) REFERENCES achimfritz_championship_tip_domain_model_tipgroup (persistence_object_identifier)");
		$this->addSql("ALTER TABLE achimfritz_championship_tip_domain_model_ranking DROP FOREIGN KEY FK_B5BAA8C78D93D649");
		$this->addSql("DROP INDEX idx_b5baa8c78d93d649 ON achimfritz_championship_tip_domain_model_ranking");
		$this->addSql("CREATE INDEX IDX_22037E8D93D649 ON achimfritz_championship_tip_domain_model_ranking (user)");
		$this->addSql("ALTER TABLE achimfritz_championship_tip_domain_model_ranking ADD CONSTRAINT FK_B5BAA8C78D93D649 FOREIGN KEY (user) REFERENCES achimfritz_championship_user_domain_model_user (persistence_object_identifier)");
		$this->addSql("ALTER TABLE achimfritz_championship_tip_domain_model_tip DROP FOREIGN KEY FK_1ADA9F058D93D649");
		$this->addSql("ALTER TABLE achimfritz_championship_tip_domain_model_tip DROP FOREIGN KEY FK_1ADA9F05DFBDA53F");
		$this->addSql("ALTER TABLE achimfritz_championship_tip_domain_model_tip DROP FOREIGN KEY FK_1ADA9F05136AC113");
		$this->addSql("DROP INDEX uniq_1ada9f05136ac113 ON achimfritz_championship_tip_domain_model_tip");
		$this->addSql("CREATE UNIQUE INDEX UNIQ_9226C7D7136AC113 ON achimfritz_championship_tip_domain_model_tip (result)");
		$this->addSql("DROP INDEX idx_1ada9f058d93d649 ON achimfritz_championship_tip_domain_model_tip");
		$this->addSql("CREATE INDEX IDX_9226C7D78D93D649 ON achimfritz_championship_tip_domain_model_tip (user)");
		$this->addSql("DROP INDEX idx_1ada9f05dfbda53f ON achimfritz_championship_tip_domain_model_tip");
		$this->addSql("CREATE INDEX IDX_9226C7D7DFBDA53F ON achimfritz_championship_tip_domain_model_tip (generalmatch)");
		$this->addSql("ALTER TABLE achimfritz_championship_tip_domain_model_tip ADD CONSTRAINT FK_1ADA9F058D93D649 FOREIGN KEY (user) REFERENCES achimfritz_championship_user_domain_model_user (persistence_object_identifier)");
		$this->addSql("ALTER TABLE achimfritz_championship_tip_domain_model_tip ADD CONSTRAINT FK_1ADA9F05DFBDA53F FOREIGN KEY (generalmatch) REFERENCES achimfritz_championship_competition_domain_model_match (persistence_object_identifier)");
		$this->addSql("ALTER TABLE achimfritz_championship_tip_domain_model_tip ADD CONSTRAINT FK_1ADA9F05136AC113 FOREIGN KEY (result) REFERENCES achimfritz_championship_competition_domain_model_result (persistence_object_identifier)");
		$this->addSql("ALTER TABLE achimfritz_championship_tip_domain_model_tipgr_c2a81_users_join DROP FOREIGN KEY FK_7B25C34045E83D34");
		$this->addSql("ALTER TABLE achimfritz_championship_tip_domain_model_tipgr_c2a81_users_join DROP FOREIGN KEY FK_7B25C340F7129A80");
		$this->addSql("DROP INDEX idx_7b25c34045e83d34 ON achimfritz_championship_tip_domain_model_tipgr_c2a81_users_join");
		$this->addSql("CREATE INDEX IDX_6F435DBC246893B3 ON achimfritz_championship_tip_domain_model_tipgr_c2a81_users_join (tip_tipgroupresultmatrix)");
		$this->addSql("DROP INDEX idx_7b25c340f7129a80 ON achimfritz_championship_tip_domain_model_tipgr_c2a81_users_join");
		$this->addSql("CREATE INDEX IDX_6F435DBCA995E300 ON achimfritz_championship_tip_domain_model_tipgr_c2a81_users_join (user_user)");
		$this->addSql("ALTER TABLE achimfritz_championship_tip_domain_model_tipgr_c2a81_users_join ADD CONSTRAINT FK_7B25C34045E83D34 FOREIGN KEY (tip_tipgroupresultmatrix) REFERENCES achimfritz_championship_tip_domain_model_tipgroupresultmatrix (persistence_object_identifier)");
		$this->addSql("ALTER TABLE achimfritz_championship_tip_domain_model_tipgr_c2a81_users_join ADD CONSTRAINT FK_7B25C340F7129A80 FOREIGN KEY (user_user) REFERENCES achimfritz_championship_user_domain_model_user (persistence_object_identifier)");
		$this->addSql("ALTER TABLE achimfritz_championship_tip_domain_model_tipgro_c2a81_rows_join DROP FOREIGN KEY FK_E50D217345E83D34");
		$this->addSql("ALTER TABLE achimfritz_championship_tip_domain_model_tipgro_c2a81_rows_join DROP FOREIGN KEY FK_E50D2173636B9926");
		$this->addSql("DROP INDEX idx_e50d217345e83d34 ON achimfritz_championship_tip_domain_model_tipgro_c2a81_rows_join");
		$this->addSql("CREATE INDEX IDX_A8E08DB6246893B3 ON achimfritz_championship_tip_domain_model_tipgro_c2a81_rows_join (tip_tipgroupresultmatrix)");
		$this->addSql("DROP INDEX idx_e50d2173636b9926 ON achimfritz_championship_tip_domain_model_tipgro_c2a81_rows_join");
		$this->addSql("CREATE INDEX IDX_A8E08DB65A2D8605 ON achimfritz_championship_tip_domain_model_tipgro_c2a81_rows_join (tip_tipgroupresultmatrixrow)");
		$this->addSql("ALTER TABLE achimfritz_championship_tip_domain_model_tipgro_c2a81_rows_join ADD CONSTRAINT FK_E50D217345E83D34 FOREIGN KEY (tip_tipgroupresultmatrix) REFERENCES achimfritz_championship_tip_domain_model_tipgroupresultmatrix (persistence_object_identifier)");
		$this->addSql("ALTER TABLE achimfritz_championship_tip_domain_model_tipgro_c2a81_rows_join ADD CONSTRAINT FK_E50D2173636B9926 FOREIGN KEY (tip_tipgroupresultmatrixrow) REFERENCES achimfritz_championship_tip_domain_model_tipgroupresultma_d24a5 (persistence_object_identifier)");
		$this->addSql("ALTER TABLE achimfritz_championship_tip_domain_model_tipgro_d24a5_tips_join DROP FOREIGN KEY FK_B70F797636B9926");
		$this->addSql("ALTER TABLE achimfritz_championship_tip_domain_model_tipgro_d24a5_tips_join DROP FOREIGN KEY FK_B70F79777CEEBB1");
		$this->addSql("DROP INDEX idx_b70f797636b9926 ON achimfritz_championship_tip_domain_model_tipgro_d24a5_tips_join");
		$this->addSql("CREATE INDEX IDX_52665F765A2D8605 ON achimfritz_championship_tip_domain_model_tipgro_d24a5_tips_join (tip_tipgroupresultmatrixrow)");
		$this->addSql("DROP INDEX idx_b70f79777ceebb1 ON achimfritz_championship_tip_domain_model_tipgro_d24a5_tips_join");
		$this->addSql("CREATE INDEX IDX_52665F76FA1557BF ON achimfritz_championship_tip_domain_model_tipgro_d24a5_tips_join (tip_tip)");
		$this->addSql("ALTER TABLE achimfritz_championship_tip_domain_model_tipgro_d24a5_tips_join ADD CONSTRAINT FK_B70F797636B9926 FOREIGN KEY (tip_tipgroupresultmatrixrow) REFERENCES achimfritz_championship_tip_domain_model_tipgroupresultma_d24a5 (persistence_object_identifier)");
		$this->addSql("ALTER TABLE achimfritz_championship_tip_domain_model_tipgro_d24a5_tips_join ADD CONSTRAINT FK_B70F79777CEEBB1 FOREIGN KEY (tip_tip) REFERENCES achimfritz_championship_tip_domain_model_tip (persistence_object_identifier)");
		$this->addSql("DROP INDEX flow_identity_achimfritz_championship_tip_domain_model_tipgroup ON achimfritz_championship_tip_domain_model_tipgroup");
		$this->addSql("CREATE UNIQUE INDEX flow_identity_achimfritz_championship_domain_model_tipgroup ON achimfritz_championship_tip_domain_model_tipgroup (name)");
		$this->addSql("ALTER TABLE achimfritz_championship_tip_domain_model_tipgroupresultma_d24a5 DROP FOREIGN KEY FK_BFA4B76ADFBDA53F");
		$this->addSql("DROP INDEX uniq_bfa4b76adfbda53f ON achimfritz_championship_tip_domain_model_tipgroupresultma_d24a5");
		$this->addSql("CREATE UNIQUE INDEX UNIQ_6D37622ADFBDA53F ON achimfritz_championship_tip_domain_model_tipgroupresultma_d24a5 (generalmatch)");
		$this->addSql("ALTER TABLE achimfritz_championship_tip_domain_model_tipgroupresultma_d24a5 ADD CONSTRAINT FK_BFA4B76ADFBDA53F FOREIGN KEY (generalmatch) REFERENCES achimfritz_championship_competition_domain_model_match (persistence_object_identifier)");
		$this->addSql("ALTER TABLE achimfritz_championship_user_domain_model_password DROP FOREIGN KEY FK_28743D4A8D93D649");
		$this->addSql("DROP INDEX uniq_28743d4a8d93d649 ON achimfritz_championship_user_domain_model_password");
		$this->addSql("CREATE UNIQUE INDEX UNIQ_42C52008D93D649 ON achimfritz_championship_user_domain_model_password (user)");
		$this->addSql("ALTER TABLE achimfritz_championship_user_domain_model_password ADD CONSTRAINT FK_28743D4A8D93D649 FOREIGN KEY (user) REFERENCES achimfritz_championship_user_domain_model_user (persistence_object_identifier)");
		$this->addSql("ALTER TABLE achimfritz_championship_user_domain_model_user DROP FOREIGN KEY FK_62FB7B77D3656A4");
		$this->addSql("ALTER TABLE achimfritz_championship_user_domain_model_user DROP FOREIGN KEY FK_62FB7B7F3D6F72C");
		$this->addSql("DROP INDEX uniq_62fb7b77d3656a4 ON achimfritz_championship_user_domain_model_user");
		$this->addSql("CREATE UNIQUE INDEX UNIQ_EA9439FA7D3656A4 ON achimfritz_championship_user_domain_model_user (account)");
		$this->addSql("DROP INDEX idx_62fb7b7f3d6f72c ON achimfritz_championship_user_domain_model_user");
		$this->addSql("CREATE INDEX IDX_EA9439FAF3D6F72C ON achimfritz_championship_user_domain_model_user (tipgroup)");
		$this->addSql("ALTER TABLE achimfritz_championship_user_domain_model_user ADD CONSTRAINT FK_62FB7B77D3656A4 FOREIGN KEY (account) REFERENCES typo3_flow_security_account (persistence_object_identifier)");
		$this->addSql("ALTER TABLE achimfritz_championship_user_domain_model_user ADD CONSTRAINT FK_62FB7B7F3D6F72C FOREIGN KEY (tipgroup) REFERENCES achimfritz_championship_tip_domain_model_tipgroup (persistence_object_identifier)");
		$this->addSql("ALTER TABLE achimfritz_championship_user_domain_model_user_tipgroups_join DROP FOREIGN KEY FK_42D6DA98F7129A80");
		$this->addSql("ALTER TABLE achimfritz_championship_user_domain_model_user_tipgroups_join DROP FOREIGN KEY FK_42D6DA98BA56F723");
		$this->addSql("DROP INDEX idx_42d6da98f7129a80 ON achimfritz_championship_user_domain_model_user_tipgroups_join");
		$this->addSql("CREATE INDEX IDX_318E5079A995E300 ON achimfritz_championship_user_domain_model_user_tipgroups_join (user_user)");
		$this->addSql("DROP INDEX idx_42d6da98ba56f723 ON achimfritz_championship_user_domain_model_user_tipgroups_join");
		$this->addSql("CREATE INDEX IDX_318E50795D3384B7 ON achimfritz_championship_user_domain_model_user_tipgroups_join (tip_tipgroup)");
		$this->addSql("ALTER TABLE achimfritz_championship_user_domain_model_user_tipgroups_join ADD CONSTRAINT FK_42D6DA98F7129A80 FOREIGN KEY (user_user) REFERENCES achimfritz_championship_user_domain_model_user (persistence_object_identifier)");
		$this->addSql("ALTER TABLE achimfritz_championship_user_domain_model_user_tipgroups_join ADD CONSTRAINT FK_42D6DA98BA56F723 FOREIGN KEY (tip_tipgroup) REFERENCES achimfritz_championship_tip_domain_model_tipgroup (persistence_object_identifier)");
		$this->addSql("ALTER TABLE typo3_flow_security_account CHANGE failedauthenticationcount failedauthenticationcount INT DEFAULT 0");
	}
}