<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130525182948 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
			// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_points DROP FOREIGN KEY FK_D8E7EBBC324DB864");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_tip DROP FOREIGN KEY FK_9226C7D7324DB864");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_cup_matchtypes_join DROP FOREIGN KEY FK_7E4129AEA28840B2");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_cupmatch DROP FOREIGN KEY FK_3A3ACB1C5FBEF0D");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_points DROP FOREIGN KEY FK_D8E7EBBCC5FBEF0D");
		$this->addSql("CREATE TABLE achimfritz_championship_domain_model_match_abstractmatch (persistence_object_identifier VARCHAR(40) NOT NULL, hostteam VARCHAR(40) DEFAULT NULL, guestteam VARCHAR(40) DEFAULT NULL, cup VARCHAR(40) DEFAULT NULL, result VARCHAR(40) DEFAULT NULL, startdate DATETIME NOT NULL, INDEX IDX_451B77777F921808 (hostteam), INDEX IDX_451B777787754416 (guestteam), INDEX IDX_451B7777B79D50E4 (cup), UNIQUE INDEX UNIQ_451B7777136AC113 (result), PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("CREATE TABLE achimfritz_championship_domain_model_match_eightfinalmatch (persistence_object_identifier VARCHAR(40) NOT NULL, startdate DATETIME NOT NULL, PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("CREATE TABLE achimfritz_championship_domain_model_match_finalmatch (persistence_object_identifier VARCHAR(40) NOT NULL, startdate DATETIME NOT NULL, PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("CREATE TABLE achimfritz_championship_domain_model_match_quarterfinalmatch (persistence_object_identifier VARCHAR(40) NOT NULL, startdate DATETIME NOT NULL, PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("CREATE TABLE achimfritz_championship_domain_model_match_roundmatch (persistence_object_identifier VARCHAR(40) NOT NULL, startdate DATETIME NOT NULL, name VARCHAR(255) NOT NULL, UNIQUE INDEX flow_identity_achimfritz_championship_domain_model_match__dfb1d (name), PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("CREATE TABLE achimfritz_championship_domain_model_match_semifinalmatch (persistence_object_identifier VARCHAR(40) NOT NULL, startdate DATETIME NOT NULL, PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("CREATE TABLE achimfritz_championship_domain_model_match (persistence_object_identifier VARCHAR(40) NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_match_abstractmatch ADD CONSTRAINT FK_451B77777F921808 FOREIGN KEY (hostteam) REFERENCES achimfritz_championship_domain_model_team (persistence_object_identifier)");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_match_abstractmatch ADD CONSTRAINT FK_451B777787754416 FOREIGN KEY (guestteam) REFERENCES achimfritz_championship_domain_model_team (persistence_object_identifier)");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_match_abstractmatch ADD CONSTRAINT FK_451B7777B79D50E4 FOREIGN KEY (cup) REFERENCES achimfritz_championship_domain_model_cup (persistence_object_identifier)");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_match_abstractmatch ADD CONSTRAINT FK_451B7777136AC113 FOREIGN KEY (result) REFERENCES achimfritz_championship_domain_model_result (persistence_object_identifier)");
		$this->addSql("DROP TABLE achimfritz_championship_domain_model_cup_matchtypes_join");
		$this->addSql("DROP TABLE achimfritz_championship_domain_model_cupeightfinalmatch");
		$this->addSql("DROP TABLE achimfritz_championship_domain_model_cupfinalmatch");
		$this->addSql("DROP TABLE achimfritz_championship_domain_model_cupmatch");
		$this->addSql("DROP TABLE achimfritz_championship_domain_model_cuppreroundmatch");
		$this->addSql("DROP TABLE achimfritz_championship_domain_model_cupquarterfinalmatch");
		$this->addSql("DROP TABLE achimfritz_championship_domain_model_cupsemifinalmatch");
		$this->addSql("DROP TABLE achimfritz_championship_domain_model_matchtype");
		$this->addSql("DROP INDEX IDX_9226C7D7324DB864 ON achimfritz_championship_domain_model_tip");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_tip CHANGE cupmatch abstractmatch VARCHAR(40) DEFAULT NULL");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_tip ADD CONSTRAINT FK_9226C7D7D49AC61F FOREIGN KEY (abstractmatch) REFERENCES achimfritz_championship_domain_model_match_abstractmatch (persistence_object_identifier)");
		$this->addSql("CREATE INDEX IDX_9226C7D7D49AC61F ON achimfritz_championship_domain_model_tip (abstractmatch)");
		$this->addSql("DROP INDEX IDX_D8E7EBBC324DB864 ON achimfritz_championship_domain_model_points");
		$this->addSql("DROP INDEX IDX_D8E7EBBCC5FBEF0D ON achimfritz_championship_domain_model_points");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_points ADD abstractmatch VARCHAR(40) DEFAULT NULL, DROP cupmatch, DROP matchtype");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_points ADD CONSTRAINT FK_D8E7EBBCD49AC61F FOREIGN KEY (abstractmatch) REFERENCES achimfritz_championship_domain_model_match_abstractmatch (persistence_object_identifier)");
		$this->addSql("CREATE INDEX IDX_D8E7EBBCD49AC61F ON achimfritz_championship_domain_model_points (abstractmatch)");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
			// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_tip DROP FOREIGN KEY FK_9226C7D7D49AC61F");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_points DROP FOREIGN KEY FK_D8E7EBBCD49AC61F");
		$this->addSql("CREATE TABLE achimfritz_championship_domain_model_cup_matchtypes_join (championship_cup VARCHAR(40) NOT NULL, championship_matchtype VARCHAR(40) NOT NULL, INDEX IDX_7E4129AE50BBF17 (championship_cup), INDEX IDX_7E4129AEA28840B2 (championship_matchtype), PRIMARY KEY(championship_cup, championship_matchtype)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("CREATE TABLE achimfritz_championship_domain_model_cupeightfinalmatch (persistence_object_identifier VARCHAR(40) NOT NULL, startdate DATETIME NOT NULL, PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("CREATE TABLE achimfritz_championship_domain_model_cupfinalmatch (persistence_object_identifier VARCHAR(40) NOT NULL, startdate DATETIME NOT NULL, PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("CREATE TABLE achimfritz_championship_domain_model_cupmatch (persistence_object_identifier VARCHAR(40) NOT NULL, result VARCHAR(40) DEFAULT NULL, hostteam VARCHAR(40) DEFAULT NULL, guestteam VARCHAR(40) DEFAULT NULL, cup VARCHAR(40) DEFAULT NULL, matchtype VARCHAR(40) DEFAULT NULL, startdate DATETIME NOT NULL, UNIQUE INDEX UNIQ_3A3ACB1136AC113 (result), INDEX IDX_3A3ACB17F921808 (hostteam), INDEX IDX_3A3ACB187754416 (guestteam), INDEX IDX_3A3ACB1C5FBEF0D (matchtype), INDEX IDX_3A3ACB1B79D50E4 (cup), PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("CREATE TABLE achimfritz_championship_domain_model_cuppreroundmatch (persistence_object_identifier VARCHAR(40) NOT NULL, startdate DATETIME NOT NULL, groupname VARCHAR(255) NOT NULL, UNIQUE INDEX flow_identity_achimfritz_championship_domain_model_cuppre_0655c (groupname), PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("CREATE TABLE achimfritz_championship_domain_model_cupquarterfinalmatch (persistence_object_identifier VARCHAR(40) NOT NULL, startdate DATETIME NOT NULL, PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("CREATE TABLE achimfritz_championship_domain_model_cupsemifinalmatch (persistence_object_identifier VARCHAR(40) NOT NULL, startdate DATETIME NOT NULL, PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("CREATE TABLE achimfritz_championship_domain_model_matchtype (persistence_object_identifier VARCHAR(40) NOT NULL, name VARCHAR(255) NOT NULL, matchtype INT NOT NULL, PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_cup_matchtypes_join ADD CONSTRAINT FK_7E4129AEA28840B2 FOREIGN KEY (championship_matchtype) REFERENCES achimfritz_championship_domain_model_matchtype (persistence_object_identifier)");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_cup_matchtypes_join ADD CONSTRAINT FK_7E4129AE50BBF17 FOREIGN KEY (championship_cup) REFERENCES achimfritz_championship_domain_model_cup (persistence_object_identifier)");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_cupmatch ADD CONSTRAINT FK_3A3ACB1136AC113 FOREIGN KEY (result) REFERENCES achimfritz_championship_domain_model_result (persistence_object_identifier)");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_cupmatch ADD CONSTRAINT FK_3A3ACB17F921808 FOREIGN KEY (hostteam) REFERENCES achimfritz_championship_domain_model_team (persistence_object_identifier)");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_cupmatch ADD CONSTRAINT FK_3A3ACB187754416 FOREIGN KEY (guestteam) REFERENCES achimfritz_championship_domain_model_team (persistence_object_identifier)");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_cupmatch ADD CONSTRAINT FK_3A3ACB1B79D50E4 FOREIGN KEY (cup) REFERENCES achimfritz_championship_domain_model_cup (persistence_object_identifier)");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_cupmatch ADD CONSTRAINT FK_3A3ACB1C5FBEF0D FOREIGN KEY (matchtype) REFERENCES achimfritz_championship_domain_model_matchtype (persistence_object_identifier)");
		$this->addSql("DROP TABLE achimfritz_championship_domain_model_match_abstractmatch");
		$this->addSql("DROP TABLE achimfritz_championship_domain_model_match_eightfinalmatch");
		$this->addSql("DROP TABLE achimfritz_championship_domain_model_match_finalmatch");
		$this->addSql("DROP TABLE achimfritz_championship_domain_model_match_quarterfinalmatch");
		$this->addSql("DROP TABLE achimfritz_championship_domain_model_match_roundmatch");
		$this->addSql("DROP TABLE achimfritz_championship_domain_model_match_semifinalmatch");
		$this->addSql("DROP TABLE achimfritz_championship_domain_model_match");
		$this->addSql("DROP INDEX IDX_D8E7EBBCD49AC61F ON achimfritz_championship_domain_model_points");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_points CHANGE abstractmatch matchtype VARCHAR(40) DEFAULT NULL");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_points ADD CONSTRAINT FK_D8E7EBBC324DB864 FOREIGN KEY (cupmatch) REFERENCES achimfritz_championship_domain_model_cupmatch (persistence_object_identifier)");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_points ADD CONSTRAINT FK_D8E7EBBCC5FBEF0D FOREIGN KEY (matchtype) REFERENCES achimfritz_championship_domain_model_matchtype (persistence_object_identifier)");
		$this->addSql("CREATE INDEX IDX_D8E7EBBC324DB864 ON achimfritz_championship_domain_model_points (cupmatch)");
		$this->addSql("CREATE INDEX IDX_D8E7EBBCC5FBEF0D ON achimfritz_championship_domain_model_points (matchtype)");
		$this->addSql("DROP INDEX IDX_9226C7D7D49AC61F ON achimfritz_championship_domain_model_tip");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_tip CHANGE abstractmatch cupmatch VARCHAR(40) DEFAULT NULL");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_tip ADD CONSTRAINT FK_9226C7D7324DB864 FOREIGN KEY (cupmatch) REFERENCES achimfritz_championship_domain_model_cupmatch (persistence_object_identifier)");
		$this->addSql("CREATE INDEX IDX_9226C7D7324DB864 ON achimfritz_championship_domain_model_tip (cupmatch)");
	}
}

?>