<?php
namespace Neos\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140530113008 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
			// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("CREATE TABLE achimfritz_championship_domain_model_chatentry (persistence_object_identifier VARCHAR(40) NOT NULL, user VARCHAR(40) DEFAULT NULL, message VARCHAR(255) NOT NULL, creationdate DATETIME NOT NULL, dtype VARCHAR(255) NOT NULL, INDEX IDX_2610B8658D93D649 (user), PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("CREATE TABLE achimfritz_championship_domain_model_contactrequest (persistence_object_identifier VARCHAR(40) NOT NULL, email VARCHAR(255) NOT NULL, subject VARCHAR(255) NOT NULL, message VARCHAR(255) NOT NULL, creationdate DATETIME NOT NULL, PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("CREATE TABLE achimfritz_championship_domain_model_openchatentry (persistence_object_identifier VARCHAR(40) NOT NULL, PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("CREATE TABLE achimfritz_championship_domain_model_registrationrequest (persistence_object_identifier VARCHAR(40) NOT NULL, newpassword VARCHAR(255) NOT NULL, newpasswordrepeat VARCHAR(255) NOT NULL, creationdate DATETIME NOT NULL, tipgroupname VARCHAR(255) NOT NULL, email VARCHAR(255) NOT NULL, username VARCHAR(255) NOT NULL, PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("CREATE TABLE achimfritz_championship_domain_model_tipgroupchatentry (persistence_object_identifier VARCHAR(40) NOT NULL, tipgroup VARCHAR(40) DEFAULT NULL, INDEX IDX_203E73E3F3D6F72C (tipgroup), PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_chatentry ADD CONSTRAINT FK_2610B8658D93D649 FOREIGN KEY (user) REFERENCES achimfritz_championship_domain_model_user (persistence_object_identifier)");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_openchatentry ADD CONSTRAINT FK_21CE68D947A46B0A FOREIGN KEY (persistence_object_identifier) REFERENCES achimfritz_championship_domain_model_chatentry (persistence_object_identifier) ON DELETE CASCADE");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_tipgroupchatentry ADD CONSTRAINT FK_203E73E3F3D6F72C FOREIGN KEY (tipgroup) REFERENCES achimfritz_championship_domain_model_tipgroup (persistence_object_identifier)");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_tipgroupchatentry ADD CONSTRAINT FK_203E73E347A46B0A FOREIGN KEY (persistence_object_identifier) REFERENCES achimfritz_championship_domain_model_chatentry (persistence_object_identifier) ON DELETE CASCADE");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
			// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_openchatentry DROP FOREIGN KEY FK_21CE68D947A46B0A");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_tipgroupchatentry DROP FOREIGN KEY FK_203E73E347A46B0A");
		$this->addSql("DROP TABLE achimfritz_championship_domain_model_chatentry");
		$this->addSql("DROP TABLE achimfritz_championship_domain_model_contactrequest");
		$this->addSql("DROP TABLE achimfritz_championship_domain_model_openchatentry");
		$this->addSql("DROP TABLE achimfritz_championship_domain_model_registrationrequest");
		$this->addSql("DROP TABLE achimfritz_championship_domain_model_tipgroupchatentry");
	}
}

?>