<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140114192412 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
			// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_teamsoftwomatchesmatch DROP INDEX UNIQ_7BB97C90F933327C, ADD INDEX IDX_7BB97C90F933327C (hostmatch)");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_teamsoftwomatchesmatch DROP INDEX UNIQ_7BB97C903C4E843, ADD INDEX IDX_7BB97C903C4E843 (guestmatch)");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
			// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_teamsoftwomatchesmatch DROP INDEX IDX_7BB97C90F933327C, ADD UNIQUE INDEX UNIQ_7BB97C90F933327C (hostmatch)");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_teamsoftwomatchesmatch DROP INDEX IDX_7BB97C903C4E843, ADD UNIQUE INDEX UNIQ_7BB97C903C4E843 (guestmatch)");
	}
}

?>