<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140417181430 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
			// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_ranking DROP FOREIGN KEY FK_22037EB79D50E4");
		$this->addSql("DROP INDEX IDX_22037EB79D50E4 ON achimfritz_championship_domain_model_ranking");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_ranking ADD rank INT NOT NULL, DROP cup");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_tip ADD points INT NOT NULL");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
			// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_ranking ADD cup VARCHAR(40) DEFAULT NULL, DROP rank");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_ranking ADD CONSTRAINT FK_22037EB79D50E4 FOREIGN KEY (cup) REFERENCES achimfritz_championship_domain_model_cup (persistence_object_identifier)");
		$this->addSql("CREATE INDEX IDX_22037EB79D50E4 ON achimfritz_championship_domain_model_ranking (cup)");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_tip DROP points");
	}
}

?>