<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130526152612 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
			// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_match ADD dtype VARCHAR(255) NOT NULL");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_match_eightfinalmatch DROP startdate, DROP hostteamalt, DROP guestteamalt");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_match_eightfinalmatch ADD CONSTRAINT FK_8150D77A47A46B0A FOREIGN KEY (persistence_object_identifier) REFERENCES achimfritz_championship_domain_model_match (persistence_object_identifier) ON DELETE CASCADE");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_match_finalmatch DROP startdate, DROP hostteamalt, DROP guestteamalt");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_match_finalmatch ADD CONSTRAINT FK_C822C31247A46B0A FOREIGN KEY (persistence_object_identifier) REFERENCES achimfritz_championship_domain_model_match (persistence_object_identifier) ON DELETE CASCADE");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_match_quarterfinalmatch DROP startdate, DROP hostteamalt, DROP guestteamalt");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_match_quarterfinalmatch ADD CONSTRAINT FK_8BBC9F6347A46B0A FOREIGN KEY (persistence_object_identifier) REFERENCES achimfritz_championship_domain_model_match (persistence_object_identifier) ON DELETE CASCADE");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_match_semifinalmatch DROP startdate, DROP hostteamalt, DROP guestteamalt");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_match_semifinalmatch ADD CONSTRAINT FK_8D2360BD47A46B0A FOREIGN KEY (persistence_object_identifier) REFERENCES achimfritz_championship_domain_model_match (persistence_object_identifier) ON DELETE CASCADE");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
			// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_match DROP dtype");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_match_eightfinalmatch DROP FOREIGN KEY FK_8150D77A47A46B0A");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_match_eightfinalmatch ADD startdate DATETIME NOT NULL, ADD hostteamalt VARCHAR(255) NOT NULL, ADD guestteamalt VARCHAR(255) NOT NULL");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_match_finalmatch DROP FOREIGN KEY FK_C822C31247A46B0A");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_match_finalmatch ADD startdate DATETIME NOT NULL, ADD hostteamalt VARCHAR(255) NOT NULL, ADD guestteamalt VARCHAR(255) NOT NULL");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_match_quarterfinalmatch DROP FOREIGN KEY FK_8BBC9F6347A46B0A");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_match_quarterfinalmatch ADD startdate DATETIME NOT NULL, ADD hostteamalt VARCHAR(255) NOT NULL, ADD guestteamalt VARCHAR(255) NOT NULL");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_match_semifinalmatch DROP FOREIGN KEY FK_8D2360BD47A46B0A");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_match_semifinalmatch ADD startdate DATETIME NOT NULL, ADD hostteamalt VARCHAR(255) NOT NULL, ADD guestteamalt VARCHAR(255) NOT NULL");
	}
}

?>