<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130529182133 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
			// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("CREATE TABLE achimfritz_championship_domain_model_koround (persistence_object_identifier VARCHAR(40) NOT NULL, parentround VARCHAR(40) DEFAULT NULL, UNIQUE INDEX UNIQ_6E295D69A528AC9B (parentround), PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_koround ADD CONSTRAINT FK_6E295D69A528AC9B FOREIGN KEY (parentround) REFERENCES achimfritz_championship_domain_model_koround (persistence_object_identifier)");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_koround ADD CONSTRAINT FK_6E295D6947A46B0A FOREIGN KEY (persistence_object_identifier) REFERENCES achimfritz_championship_domain_model_round (persistence_object_identifier) ON DELETE CASCADE");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_round DROP FOREIGN KEY FK_97E10FED8256A42D");
		$this->addSql("DROP INDEX UNIQ_97E10FED8256A42D ON achimfritz_championship_domain_model_round");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_round DROP grouptable");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_groupround ADD grouptable VARCHAR(40) DEFAULT NULL, ADD groupnname VARCHAR(255) NOT NULL");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_groupround ADD CONSTRAINT FK_570415968256A42D FOREIGN KEY (grouptable) REFERENCES achimfritz_championship_domain_model_grouptable (persistence_object_identifier)");
		$this->addSql("CREATE UNIQUE INDEX UNIQ_570415968256A42D ON achimfritz_championship_domain_model_groupround (grouptable)");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
			// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_koround DROP FOREIGN KEY FK_6E295D69A528AC9B");
		$this->addSql("DROP TABLE achimfritz_championship_domain_model_koround");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_groupround DROP FOREIGN KEY FK_570415968256A42D");
		$this->addSql("DROP INDEX UNIQ_570415968256A42D ON achimfritz_championship_domain_model_groupround");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_groupround DROP grouptable, DROP groupnname");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_round ADD grouptable VARCHAR(40) DEFAULT NULL");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_round ADD CONSTRAINT FK_97E10FED8256A42D FOREIGN KEY (grouptable) REFERENCES achimfritz_championship_domain_model_grouptable (persistence_object_identifier)");
		$this->addSql("CREATE UNIQUE INDEX UNIQ_97E10FED8256A42D ON achimfritz_championship_domain_model_round (grouptable)");
	}
}

?>