<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130525175554 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
			// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("CREATE TABLE achimfritz_championship_domain_model_cupeightfinalmatch (persistence_object_identifier VARCHAR(40) NOT NULL, startdate DATETIME NOT NULL, PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("CREATE TABLE achimfritz_championship_domain_model_cupfinalmatch (persistence_object_identifier VARCHAR(40) NOT NULL, startdate DATETIME NOT NULL, PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("CREATE TABLE achimfritz_championship_domain_model_cuppreroundmatch (persistence_object_identifier VARCHAR(40) NOT NULL, startdate DATETIME NOT NULL, groupname VARCHAR(255) NOT NULL, UNIQUE INDEX flow_identity_achimfritz_championship_domain_model_cuppre_0655c (groupname), PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("CREATE TABLE achimfritz_championship_domain_model_cupquarterfinalmatch (persistence_object_identifier VARCHAR(40) NOT NULL, startdate DATETIME NOT NULL, PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("CREATE TABLE achimfritz_championship_domain_model_cupsemifinalmatch (persistence_object_identifier VARCHAR(40) NOT NULL, startdate DATETIME NOT NULL, PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
			// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("DROP TABLE achimfritz_championship_domain_model_cupeightfinalmatch");
		$this->addSql("DROP TABLE achimfritz_championship_domain_model_cupfinalmatch");
		$this->addSql("DROP TABLE achimfritz_championship_domain_model_cuppreroundmatch");
		$this->addSql("DROP TABLE achimfritz_championship_domain_model_cupquarterfinalmatch");
		$this->addSql("DROP TABLE achimfritz_championship_domain_model_cupsemifinalmatch");
	}
}

?>