<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130528200239 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
			// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("CREATE TABLE achimfritz_championship_domain_model_grouptable (persistence_object_identifier VARCHAR(40) NOT NULL, PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("CREATE TABLE achimfritz_championship_domain_model_grouptablerow (persistence_object_identifier VARCHAR(40) NOT NULL, grouptable VARCHAR(40) DEFAULT NULL, goalsplus INT NOT NULL, points INT NOT NULL, rank INT NOT NULL, INDEX IDX_789643F8256A42D (grouptable), PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("CREATE TABLE achimfritz_championship_domain_model_grouptablerow_team_join (championship_grouptablerow VARCHAR(40) NOT NULL, championship_team VARCHAR(40) NOT NULL, INDEX IDX_A5B824D3BC373499 (championship_grouptablerow), INDEX IDX_A5B824D3E0E69356 (championship_team), PRIMARY KEY(championship_grouptablerow, championship_team)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("CREATE TABLE achimfritz_championship_domain_model_matchparticipant (persistence_object_identifier VARCHAR(40) NOT NULL, winnerofmatch VARCHAR(40) DEFAULT NULL, looserofmatch VARCHAR(40) DEFAULT NULL, groupround VARCHAR(40) DEFAULT NULL, name VARCHAR(255) NOT NULL, rankofgroupround INT NOT NULL, UNIQUE INDEX UNIQ_98AA7B24572F536F (winnerofmatch), UNIQUE INDEX UNIQ_98AA7B24F8023A6E (looserofmatch), UNIQUE INDEX UNIQ_98AA7B24B191C15F (groupround), PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("CREATE TABLE achimfritz_championship_domain_model_matchparticipant_team_join (championship_matchparticipant VARCHAR(40) NOT NULL, championship_team VARCHAR(40) NOT NULL, INDEX IDX_67F6B00CD33D9992 (championship_matchparticipant), INDEX IDX_67F6B00CE0E69356 (championship_team), PRIMARY KEY(championship_matchparticipant, championship_team)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("CREATE TABLE achimfritz_championship_domain_model_round (persistence_object_identifier VARCHAR(40) NOT NULL, grouptable VARCHAR(40) DEFAULT NULL, generalmatches VARCHAR(40) DEFAULT NULL, cup VARCHAR(40) DEFAULT NULL, name VARCHAR(255) NOT NULL, dtype VARCHAR(255) NOT NULL, UNIQUE INDEX UNIQ_97E10FED8256A42D (grouptable), INDEX IDX_97E10FED6E3D0F7D (generalmatches), UNIQUE INDEX UNIQ_97E10FEDB79D50E4 (cup), PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("CREATE TABLE achimfritz_championship_domain_model_round_teams_join (championship_round VARCHAR(40) NOT NULL, championship_team VARCHAR(40) NOT NULL, INDEX IDX_B4C549D4CACA1535 (championship_round), INDEX IDX_B4C549D4E0E69356 (championship_team), PRIMARY KEY(championship_round, championship_team)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("CREATE TABLE achimfritz_championship_domain_model_groupround (persistence_object_identifier VARCHAR(40) NOT NULL, PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_grouptablerow ADD CONSTRAINT FK_789643F8256A42D FOREIGN KEY (grouptable) REFERENCES achimfritz_championship_domain_model_grouptable (persistence_object_identifier)");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_grouptablerow_team_join ADD CONSTRAINT FK_A5B824D3BC373499 FOREIGN KEY (championship_grouptablerow) REFERENCES achimfritz_championship_domain_model_grouptablerow (persistence_object_identifier)");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_grouptablerow_team_join ADD CONSTRAINT FK_A5B824D3E0E69356 FOREIGN KEY (championship_team) REFERENCES achimfritz_championship_domain_model_team (persistence_object_identifier)");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_matchparticipant ADD CONSTRAINT FK_98AA7B24572F536F FOREIGN KEY (winnerofmatch) REFERENCES achimfritz_championship_domain_model_match (persistence_object_identifier)");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_matchparticipant ADD CONSTRAINT FK_98AA7B24F8023A6E FOREIGN KEY (looserofmatch) REFERENCES achimfritz_championship_domain_model_match (persistence_object_identifier)");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_matchparticipant ADD CONSTRAINT FK_98AA7B24B191C15F FOREIGN KEY (groupround) REFERENCES achimfritz_championship_domain_model_groupround (persistence_object_identifier)");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_matchparticipant_team_join ADD CONSTRAINT FK_67F6B00CD33D9992 FOREIGN KEY (championship_matchparticipant) REFERENCES achimfritz_championship_domain_model_matchparticipant (persistence_object_identifier)");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_matchparticipant_team_join ADD CONSTRAINT FK_67F6B00CE0E69356 FOREIGN KEY (championship_team) REFERENCES achimfritz_championship_domain_model_team (persistence_object_identifier)");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_round ADD CONSTRAINT FK_97E10FED8256A42D FOREIGN KEY (grouptable) REFERENCES achimfritz_championship_domain_model_grouptable (persistence_object_identifier)");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_round ADD CONSTRAINT FK_97E10FED6E3D0F7D FOREIGN KEY (generalmatches) REFERENCES achimfritz_championship_domain_model_match (persistence_object_identifier)");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_round ADD CONSTRAINT FK_97E10FEDB79D50E4 FOREIGN KEY (cup) REFERENCES achimfritz_championship_domain_model_cup (persistence_object_identifier)");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_round_teams_join ADD CONSTRAINT FK_B4C549D4CACA1535 FOREIGN KEY (championship_round) REFERENCES achimfritz_championship_domain_model_round (persistence_object_identifier)");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_round_teams_join ADD CONSTRAINT FK_B4C549D4E0E69356 FOREIGN KEY (championship_team) REFERENCES achimfritz_championship_domain_model_team (persistence_object_identifier)");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_groupround ADD CONSTRAINT FK_5704159647A46B0A FOREIGN KEY (persistence_object_identifier) REFERENCES achimfritz_championship_domain_model_round (persistence_object_identifier) ON DELETE CASCADE");
		$this->addSql("DROP TABLE achimfritz_championship_domain_model_match_eightfinalmatch");
		$this->addSql("DROP TABLE achimfritz_championship_domain_model_match_finalmatch");
		$this->addSql("DROP TABLE achimfritz_championship_domain_model_match_quarterfinalmatch");
		$this->addSql("DROP TABLE achimfritz_championship_domain_model_match_roundmatch");
		$this->addSql("DROP TABLE achimfritz_championship_domain_model_match_semifinalmatch");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_match DROP FOREIGN KEY FK_285420DC7F921808");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_match DROP FOREIGN KEY FK_285420DC87754416");
		$this->addSql("DROP INDEX IDX_285420DC7F921808 ON achimfritz_championship_domain_model_match");
		$this->addSql("DROP INDEX IDX_285420DC87754416 ON achimfritz_championship_domain_model_match");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_match ADD hostparticipant VARCHAR(40) DEFAULT NULL, ADD guestparticipant VARCHAR(40) DEFAULT NULL, DROP hostteam, DROP guestteam, DROP guestteamalt, DROP hostteamalt, DROP dtype");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_match ADD CONSTRAINT FK_285420DC1C47C160 FOREIGN KEY (hostparticipant) REFERENCES achimfritz_championship_domain_model_matchparticipant (persistence_object_identifier)");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_match ADD CONSTRAINT FK_285420DC89CCCBF8 FOREIGN KEY (guestparticipant) REFERENCES achimfritz_championship_domain_model_matchparticipant (persistence_object_identifier)");
		$this->addSql("CREATE UNIQUE INDEX UNIQ_285420DC1C47C160 ON achimfritz_championship_domain_model_match (hostparticipant)");
		$this->addSql("CREATE UNIQUE INDEX UNIQ_285420DC89CCCBF8 ON achimfritz_championship_domain_model_match (guestparticipant)");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
			// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_grouptablerow DROP FOREIGN KEY FK_789643F8256A42D");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_round DROP FOREIGN KEY FK_97E10FED8256A42D");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_grouptablerow_team_join DROP FOREIGN KEY FK_A5B824D3BC373499");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_match DROP FOREIGN KEY FK_285420DC1C47C160");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_match DROP FOREIGN KEY FK_285420DC89CCCBF8");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_matchparticipant_team_join DROP FOREIGN KEY FK_67F6B00CD33D9992");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_round_teams_join DROP FOREIGN KEY FK_B4C549D4CACA1535");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_groupround DROP FOREIGN KEY FK_5704159647A46B0A");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_matchparticipant DROP FOREIGN KEY FK_98AA7B24B191C15F");
		$this->addSql("CREATE TABLE achimfritz_championship_domain_model_match_eightfinalmatch (persistence_object_identifier VARCHAR(40) NOT NULL, PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("CREATE TABLE achimfritz_championship_domain_model_match_finalmatch (persistence_object_identifier VARCHAR(40) NOT NULL, PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("CREATE TABLE achimfritz_championship_domain_model_match_quarterfinalmatch (persistence_object_identifier VARCHAR(40) NOT NULL, PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("CREATE TABLE achimfritz_championship_domain_model_match_roundmatch (persistence_object_identifier VARCHAR(40) NOT NULL, name VARCHAR(255) NOT NULL, UNIQUE INDEX flow_identity_achimfritz_championship_domain_model_match__dfb1d (name), PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("CREATE TABLE achimfritz_championship_domain_model_match_semifinalmatch (persistence_object_identifier VARCHAR(40) NOT NULL, PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_match_eightfinalmatch ADD CONSTRAINT FK_8150D77A47A46B0A FOREIGN KEY (persistence_object_identifier) REFERENCES achimfritz_championship_domain_model_match (persistence_object_identifier) ON DELETE CASCADE");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_match_finalmatch ADD CONSTRAINT FK_C822C31247A46B0A FOREIGN KEY (persistence_object_identifier) REFERENCES achimfritz_championship_domain_model_match (persistence_object_identifier) ON DELETE CASCADE");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_match_quarterfinalmatch ADD CONSTRAINT FK_8BBC9F6347A46B0A FOREIGN KEY (persistence_object_identifier) REFERENCES achimfritz_championship_domain_model_match (persistence_object_identifier) ON DELETE CASCADE");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_match_roundmatch ADD CONSTRAINT FK_AEB744F347A46B0A FOREIGN KEY (persistence_object_identifier) REFERENCES achimfritz_championship_domain_model_match (persistence_object_identifier) ON DELETE CASCADE");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_match_semifinalmatch ADD CONSTRAINT FK_8D2360BD47A46B0A FOREIGN KEY (persistence_object_identifier) REFERENCES achimfritz_championship_domain_model_match (persistence_object_identifier) ON DELETE CASCADE");
		$this->addSql("DROP TABLE achimfritz_championship_domain_model_grouptable");
		$this->addSql("DROP TABLE achimfritz_championship_domain_model_grouptablerow");
		$this->addSql("DROP TABLE achimfritz_championship_domain_model_grouptablerow_team_join");
		$this->addSql("DROP TABLE achimfritz_championship_domain_model_matchparticipant");
		$this->addSql("DROP TABLE achimfritz_championship_domain_model_matchparticipant_team_join");
		$this->addSql("DROP TABLE achimfritz_championship_domain_model_round");
		$this->addSql("DROP TABLE achimfritz_championship_domain_model_round_teams_join");
		$this->addSql("DROP TABLE achimfritz_championship_domain_model_groupround");
		$this->addSql("DROP INDEX UNIQ_285420DC1C47C160 ON achimfritz_championship_domain_model_match");
		$this->addSql("DROP INDEX UNIQ_285420DC89CCCBF8 ON achimfritz_championship_domain_model_match");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_match ADD hostteam VARCHAR(40) DEFAULT NULL, ADD guestteam VARCHAR(40) DEFAULT NULL, ADD guestteamalt VARCHAR(255) NOT NULL, ADD hostteamalt VARCHAR(255) NOT NULL, ADD dtype VARCHAR(255) NOT NULL, DROP hostparticipant, DROP guestparticipant");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_match ADD CONSTRAINT FK_285420DC7F921808 FOREIGN KEY (hostteam) REFERENCES achimfritz_championship_domain_model_team (persistence_object_identifier)");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_match ADD CONSTRAINT FK_285420DC87754416 FOREIGN KEY (guestteam) REFERENCES achimfritz_championship_domain_model_team (persistence_object_identifier)");
		$this->addSql("CREATE INDEX IDX_285420DC7F921808 ON achimfritz_championship_domain_model_match (hostteam)");
		$this->addSql("CREATE INDEX IDX_285420DC87754416 ON achimfritz_championship_domain_model_match (guestteam)");
	}
}

?>