<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130531193116 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
			// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_groupround DROP FOREIGN KEY FK_570415968256A42D");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_grouptablerow DROP FOREIGN KEY FK_789643F8256A42D");
		$this->addSql("DROP TABLE achimfritz_championship_domain_model_grouptable");
		$this->addSql("DROP INDEX IDX_789643F8256A42D ON achimfritz_championship_domain_model_grouptablerow");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_grouptablerow CHANGE grouptable round VARCHAR(40) DEFAULT NULL");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_grouptablerow ADD CONSTRAINT FK_789643FC5EEEA34 FOREIGN KEY (round) REFERENCES achimfritz_championship_domain_model_round (persistence_object_identifier)");
		$this->addSql("CREATE INDEX IDX_789643FC5EEEA34 ON achimfritz_championship_domain_model_grouptablerow (round)");
		$this->addSql("DROP INDEX UNIQ_570415968256A42D ON achimfritz_championship_domain_model_groupround");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_groupround DROP grouptable");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
			// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("CREATE TABLE achimfritz_championship_domain_model_grouptable (persistence_object_identifier VARCHAR(40) NOT NULL, PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_groupround ADD grouptable VARCHAR(40) DEFAULT NULL");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_groupround ADD CONSTRAINT FK_570415968256A42D FOREIGN KEY (grouptable) REFERENCES achimfritz_championship_domain_model_grouptable (persistence_object_identifier)");
		$this->addSql("CREATE UNIQUE INDEX UNIQ_570415968256A42D ON achimfritz_championship_domain_model_groupround (grouptable)");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_grouptablerow DROP FOREIGN KEY FK_789643FC5EEEA34");
		$this->addSql("DROP INDEX IDX_789643FC5EEEA34 ON achimfritz_championship_domain_model_grouptablerow");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_grouptablerow CHANGE round grouptable VARCHAR(40) DEFAULT NULL");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_grouptablerow ADD CONSTRAINT FK_789643F8256A42D FOREIGN KEY (grouptable) REFERENCES achimfritz_championship_domain_model_grouptable (persistence_object_identifier)");
		$this->addSql("CREATE INDEX IDX_789643F8256A42D ON achimfritz_championship_domain_model_grouptablerow (grouptable)");
	}
}

?>