<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130526152341 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
			// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_match_roundmatch DROP hostteamalt, DROP guestteamalt, DROP startdate");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_match_roundmatch ADD CONSTRAINT FK_AEB744F347A46B0A FOREIGN KEY (persistence_object_identifier) REFERENCES achimfritz_championship_domain_model_match (persistence_object_identifier) ON DELETE CASCADE");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
			// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_match_roundmatch DROP FOREIGN KEY FK_AEB744F347A46B0A");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_match_roundmatch ADD hostteamalt VARCHAR(255) NOT NULL, ADD guestteamalt VARCHAR(255) NOT NULL, ADD startdate DATETIME NOT NULL");
	}
}

?>