<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130524200809 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
			// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("CREATE TABLE achimfritz_championship_domain_model_team (persistence_object_identifier VARCHAR(40) NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("CREATE TABLE achimfritz_surf_application_imageapplication (persistence_object_identifier VARCHAR(40) NOT NULL, mountpoint VARCHAR(255) NOT NULL, origpath VARCHAR(255) NOT NULL, mainpath VARCHAR(255) NOT NULL, adminpath VARCHAR(255) NOT NULL, target VARCHAR(255) NOT NULL, isexif TINYINT(1) NOT NULL, name VARCHAR(255) NOT NULL, nodes LONGTEXT NOT NULL COMMENT '(DC2Type:array)', deploymentpath VARCHAR(255) NOT NULL, options LONGTEXT NOT NULL COMMENT '(DC2Type:array)', PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("CREATE TABLE achimfritz_surf_domain_model_imageoneworkflow (persistence_object_identifier VARCHAR(40) NOT NULL, stages LONGTEXT NOT NULL COMMENT '(DC2Type:array)', enablerollback TINYINT(1) NOT NULL, tasks LONGTEXT NOT NULL COMMENT '(DC2Type:array)', PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("CREATE TABLE achimfritz_surf_domain_model_imagetwoworkflow (persistence_object_identifier VARCHAR(40) NOT NULL, stages LONGTEXT NOT NULL COMMENT '(DC2Type:array)', enablerollback TINYINT(1) NOT NULL, tasks LONGTEXT NOT NULL COMMENT '(DC2Type:array)', PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("DROP TABLE de_achimfritz_address_domain_model_address");
		$this->addSql("DROP TABLE de_achimfritz_address_domain_model_person");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
			// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("CREATE TABLE de_achimfritz_address_domain_model_address (persistence_object_identifier VARCHAR(40) NOT NULL, street VARCHAR(255) NOT NULL, city VARCHAR(255) NOT NULL, country VARCHAR(255) NOT NULL, zip VARCHAR(255) NOT NULL, housenumber VARCHAR(255) NOT NULL, PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("CREATE TABLE de_achimfritz_address_domain_model_person (persistence_object_identifier VARCHAR(40) NOT NULL, identifier VARCHAR(255) NOT NULL, addresses VARCHAR(255) NOT NULL, PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("DROP TABLE achimfritz_championship_domain_model_team");
		$this->addSql("DROP TABLE achimfritz_surf_application_imageapplication");
		$this->addSql("DROP TABLE achimfritz_surf_domain_model_imageoneworkflow");
		$this->addSql("DROP TABLE achimfritz_surf_domain_model_imagetwoworkflow");
	}
}

?>