<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20160427192359 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
		// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("ALTER TABLE achimfritz_championship_tip_domain_model_cupranking DROP FOREIGN KEY FK_4DD7491647A46B0A");
		$this->addSql("ALTER TABLE achimfritz_championship_tip_domain_model_cupranking ADD user VARCHAR(40) DEFAULT NULL, ADD points INT NOT NULL, ADD rank INT NOT NULL, ADD countoftips INT NOT NULL");
		$this->addSql("ALTER TABLE achimfritz_championship_tip_domain_model_cupranking ADD CONSTRAINT FK_4DD749168D93D649 FOREIGN KEY (user) REFERENCES achimfritz_championship_user_domain_model_user (persistence_object_identifier)");
		$this->addSql("CREATE INDEX IDX_4DD749168D93D649 ON achimfritz_championship_tip_domain_model_cupranking (user)");
		$this->addSql("ALTER TABLE achimfritz_championship_tip_domain_model_ranking DROP dtype");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
		// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("ALTER TABLE achimfritz_championship_tip_domain_model_cupranking DROP FOREIGN KEY FK_4DD749168D93D649");
		$this->addSql("DROP INDEX IDX_4DD749168D93D649 ON achimfritz_championship_tip_domain_model_cupranking");
		$this->addSql("ALTER TABLE achimfritz_championship_tip_domain_model_cupranking DROP user, DROP points, DROP rank, DROP countoftips");
		$this->addSql("ALTER TABLE achimfritz_championship_tip_domain_model_cupranking ADD CONSTRAINT FK_4DD7491647A46B0A FOREIGN KEY (persistence_object_identifier) REFERENCES achimfritz_championship_tip_domain_model_ranking (persistence_object_identifier) ON DELETE CASCADE");
		$this->addSql("ALTER TABLE achimfritz_championship_tip_domain_model_ranking ADD dtype VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci");
	}
}