<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130619121109 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
			// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("CREATE TABLE achimfritz_championship_domain_model_round (persistence_object_identifier VARCHAR(40) NOT NULL, cup VARCHAR(40) DEFAULT NULL, name VARCHAR(255) NOT NULL, dtype VARCHAR(255) NOT NULL, INDEX IDX_97E10FEDB79D50E4 (cup), PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("CREATE TABLE achimfritz_championship_domain_model_round_teams_join (championship_round VARCHAR(40) NOT NULL, championship_team VARCHAR(40) NOT NULL, INDEX IDX_B4C549D4CACA1535 (championship_round), INDEX IDX_B4C549D4E0E69356 (championship_team), PRIMARY KEY(championship_round, championship_team)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("CREATE TABLE achimfritz_championship_domain_model_koround (persistence_object_identifier VARCHAR(40) NOT NULL, parentround VARCHAR(40) DEFAULT NULL, INDEX IDX_6E295D69A528AC9B (parentround), PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("CREATE TABLE achimfritz_championship_domain_model_finalround (persistence_object_identifier VARCHAR(40) NOT NULL, PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("CREATE TABLE achimfritz_championship_domain_model_groupround (persistence_object_identifier VARCHAR(40) NOT NULL, PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("CREATE TABLE achimfritz_championship_domain_model_grouptablerow (persistence_object_identifier VARCHAR(40) NOT NULL, team VARCHAR(40) DEFAULT NULL, groupround VARCHAR(40) DEFAULT NULL, goalsplus INT NOT NULL, goalsminus INT NOT NULL, points INT NOT NULL, rank INT NOT NULL, countofmatchesplayed INT NOT NULL, INDEX IDX_789643FC4E0A61F (team), INDEX IDX_789643FB191C15F (groupround), PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("CREATE TABLE achimfritz_championship_domain_model_match (persistence_object_identifier VARCHAR(40) NOT NULL, hostparticipant VARCHAR(40) DEFAULT NULL, guestparticipant VARCHAR(40) DEFAULT NULL, cup VARCHAR(40) DEFAULT NULL, round VARCHAR(40) DEFAULT NULL, result VARCHAR(40) DEFAULT NULL, startdate DATETIME NOT NULL, name VARCHAR(255) NOT NULL, UNIQUE INDEX UNIQ_285420DC1C47C160 (hostparticipant), UNIQUE INDEX UNIQ_285420DC89CCCBF8 (guestparticipant), INDEX IDX_285420DCB79D50E4 (cup), INDEX IDX_285420DCC5EEEA34 (round), UNIQUE INDEX UNIQ_285420DC136AC113 (result), PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("CREATE TABLE achimfritz_championship_domain_model_matchparticipant (persistence_object_identifier VARCHAR(40) NOT NULL, team VARCHAR(40) DEFAULT NULL, winnerofmatch VARCHAR(40) DEFAULT NULL, looserofmatch VARCHAR(40) DEFAULT NULL, groupround VARCHAR(40) DEFAULT NULL, rankofgroupround INT NOT NULL, INDEX IDX_98AA7B24C4E0A61F (team), UNIQUE INDEX UNIQ_98AA7B24572F536F (winnerofmatch), UNIQUE INDEX UNIQ_98AA7B24F8023A6E (looserofmatch), INDEX IDX_98AA7B24B191C15F (groupround), PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("CREATE TABLE achimfritz_championship_domain_model_points (persistence_object_identifier VARCHAR(40) NOT NULL, cup VARCHAR(40) DEFAULT NULL, generalmatch VARCHAR(40) DEFAULT NULL, user VARCHAR(40) DEFAULT NULL, team VARCHAR(40) DEFAULT NULL, points INT NOT NULL, INDEX IDX_D8E7EBBCB79D50E4 (cup), INDEX IDX_D8E7EBBCDFBDA53F (generalmatch), INDEX IDX_D8E7EBBC8D93D649 (user), INDEX IDX_D8E7EBBCC4E0A61F (team), PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("CREATE TABLE achimfritz_championship_domain_model_result (persistence_object_identifier VARCHAR(40) NOT NULL, hostteamgoals INT NOT NULL, guestteamgoals INT NOT NULL, PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("CREATE TABLE achimfritz_championship_domain_model_team (persistence_object_identifier VARCHAR(40) NOT NULL, name VARCHAR(255) NOT NULL, short VARCHAR(255) NOT NULL, UNIQUE INDEX flow_identity_achimfritz_championship_domain_model_team (name), PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("CREATE TABLE achimfritz_championship_domain_model_tip (persistence_object_identifier VARCHAR(40) NOT NULL, user VARCHAR(40) DEFAULT NULL, generalmatch VARCHAR(40) DEFAULT NULL, result VARCHAR(40) DEFAULT NULL, INDEX IDX_9226C7D78D93D649 (user), INDEX IDX_9226C7D7DFBDA53F (generalmatch), UNIQUE INDEX UNIQ_9226C7D7136AC113 (result), PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("CREATE TABLE achimfritz_championship_domain_model_user (persistence_object_identifier VARCHAR(40) NOT NULL, name VARCHAR(255) NOT NULL, UNIQUE INDEX flow_identity_achimfritz_championship_domain_model_user (name), PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("CREATE TABLE achimfritz_championship_domain_model_cup (persistence_object_identifier VARCHAR(40) NOT NULL, name VARCHAR(255) NOT NULL, startdate DATETIME NOT NULL, UNIQUE INDEX flow_identity_achimfritz_championship_domain_model_cup (name), PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("CREATE TABLE achimfritz_championship_domain_model_cup_teams_join (championship_cup VARCHAR(40) NOT NULL, championship_team VARCHAR(40) NOT NULL, INDEX IDX_ACECFD7150BBF17 (championship_cup), INDEX IDX_ACECFD71E0E69356 (championship_team), PRIMARY KEY(championship_cup, championship_team)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_round ADD CONSTRAINT FK_97E10FEDB79D50E4 FOREIGN KEY (cup) REFERENCES achimfritz_championship_domain_model_cup (persistence_object_identifier)");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_round_teams_join ADD CONSTRAINT FK_B4C549D4CACA1535 FOREIGN KEY (championship_round) REFERENCES achimfritz_championship_domain_model_round (persistence_object_identifier)");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_round_teams_join ADD CONSTRAINT FK_B4C549D4E0E69356 FOREIGN KEY (championship_team) REFERENCES achimfritz_championship_domain_model_team (persistence_object_identifier)");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_koround ADD CONSTRAINT FK_6E295D69A528AC9B FOREIGN KEY (parentround) REFERENCES achimfritz_championship_domain_model_koround (persistence_object_identifier)");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_koround ADD CONSTRAINT FK_6E295D6947A46B0A FOREIGN KEY (persistence_object_identifier) REFERENCES achimfritz_championship_domain_model_round (persistence_object_identifier) ON DELETE CASCADE");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_finalround ADD CONSTRAINT FK_BD7CD8A747A46B0A FOREIGN KEY (persistence_object_identifier) REFERENCES achimfritz_championship_domain_model_round (persistence_object_identifier) ON DELETE CASCADE");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_groupround ADD CONSTRAINT FK_5704159647A46B0A FOREIGN KEY (persistence_object_identifier) REFERENCES achimfritz_championship_domain_model_round (persistence_object_identifier) ON DELETE CASCADE");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_grouptablerow ADD CONSTRAINT FK_789643FC4E0A61F FOREIGN KEY (team) REFERENCES achimfritz_championship_domain_model_team (persistence_object_identifier)");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_grouptablerow ADD CONSTRAINT FK_789643FB191C15F FOREIGN KEY (groupround) REFERENCES achimfritz_championship_domain_model_groupround (persistence_object_identifier)");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_match ADD CONSTRAINT FK_285420DC1C47C160 FOREIGN KEY (hostparticipant) REFERENCES achimfritz_championship_domain_model_matchparticipant (persistence_object_identifier)");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_match ADD CONSTRAINT FK_285420DC89CCCBF8 FOREIGN KEY (guestparticipant) REFERENCES achimfritz_championship_domain_model_matchparticipant (persistence_object_identifier)");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_match ADD CONSTRAINT FK_285420DCB79D50E4 FOREIGN KEY (cup) REFERENCES achimfritz_championship_domain_model_cup (persistence_object_identifier)");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_match ADD CONSTRAINT FK_285420DCC5EEEA34 FOREIGN KEY (round) REFERENCES achimfritz_championship_domain_model_round (persistence_object_identifier)");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_match ADD CONSTRAINT FK_285420DC136AC113 FOREIGN KEY (result) REFERENCES achimfritz_championship_domain_model_result (persistence_object_identifier)");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_matchparticipant ADD CONSTRAINT FK_98AA7B24C4E0A61F FOREIGN KEY (team) REFERENCES achimfritz_championship_domain_model_team (persistence_object_identifier)");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_matchparticipant ADD CONSTRAINT FK_98AA7B24572F536F FOREIGN KEY (winnerofmatch) REFERENCES achimfritz_championship_domain_model_match (persistence_object_identifier)");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_matchparticipant ADD CONSTRAINT FK_98AA7B24F8023A6E FOREIGN KEY (looserofmatch) REFERENCES achimfritz_championship_domain_model_match (persistence_object_identifier)");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_matchparticipant ADD CONSTRAINT FK_98AA7B24B191C15F FOREIGN KEY (groupround) REFERENCES achimfritz_championship_domain_model_groupround (persistence_object_identifier)");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_points ADD CONSTRAINT FK_D8E7EBBCB79D50E4 FOREIGN KEY (cup) REFERENCES achimfritz_championship_domain_model_cup (persistence_object_identifier)");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_points ADD CONSTRAINT FK_D8E7EBBCDFBDA53F FOREIGN KEY (generalmatch) REFERENCES achimfritz_championship_domain_model_match (persistence_object_identifier)");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_points ADD CONSTRAINT FK_D8E7EBBC8D93D649 FOREIGN KEY (user) REFERENCES achimfritz_championship_domain_model_user (persistence_object_identifier)");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_points ADD CONSTRAINT FK_D8E7EBBCC4E0A61F FOREIGN KEY (team) REFERENCES achimfritz_championship_domain_model_team (persistence_object_identifier)");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_tip ADD CONSTRAINT FK_9226C7D78D93D649 FOREIGN KEY (user) REFERENCES achimfritz_championship_domain_model_user (persistence_object_identifier)");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_tip ADD CONSTRAINT FK_9226C7D7DFBDA53F FOREIGN KEY (generalmatch) REFERENCES achimfritz_championship_domain_model_match (persistence_object_identifier)");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_tip ADD CONSTRAINT FK_9226C7D7136AC113 FOREIGN KEY (result) REFERENCES achimfritz_championship_domain_model_result (persistence_object_identifier)");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_cup_teams_join ADD CONSTRAINT FK_ACECFD7150BBF17 FOREIGN KEY (championship_cup) REFERENCES achimfritz_championship_domain_model_cup (persistence_object_identifier)");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_cup_teams_join ADD CONSTRAINT FK_ACECFD71E0E69356 FOREIGN KEY (championship_team) REFERENCES achimfritz_championship_domain_model_team (persistence_object_identifier)");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
			// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_round_teams_join DROP FOREIGN KEY FK_B4C549D4CACA1535");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_koround DROP FOREIGN KEY FK_6E295D6947A46B0A");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_finalround DROP FOREIGN KEY FK_BD7CD8A747A46B0A");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_groupround DROP FOREIGN KEY FK_5704159647A46B0A");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_match DROP FOREIGN KEY FK_285420DCC5EEEA34");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_koround DROP FOREIGN KEY FK_6E295D69A528AC9B");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_grouptablerow DROP FOREIGN KEY FK_789643FB191C15F");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_matchparticipant DROP FOREIGN KEY FK_98AA7B24B191C15F");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_matchparticipant DROP FOREIGN KEY FK_98AA7B24572F536F");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_matchparticipant DROP FOREIGN KEY FK_98AA7B24F8023A6E");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_points DROP FOREIGN KEY FK_D8E7EBBCDFBDA53F");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_tip DROP FOREIGN KEY FK_9226C7D7DFBDA53F");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_match DROP FOREIGN KEY FK_285420DC1C47C160");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_match DROP FOREIGN KEY FK_285420DC89CCCBF8");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_match DROP FOREIGN KEY FK_285420DC136AC113");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_tip DROP FOREIGN KEY FK_9226C7D7136AC113");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_round_teams_join DROP FOREIGN KEY FK_B4C549D4E0E69356");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_grouptablerow DROP FOREIGN KEY FK_789643FC4E0A61F");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_matchparticipant DROP FOREIGN KEY FK_98AA7B24C4E0A61F");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_points DROP FOREIGN KEY FK_D8E7EBBCC4E0A61F");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_cup_teams_join DROP FOREIGN KEY FK_ACECFD71E0E69356");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_points DROP FOREIGN KEY FK_D8E7EBBC8D93D649");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_tip DROP FOREIGN KEY FK_9226C7D78D93D649");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_round DROP FOREIGN KEY FK_97E10FEDB79D50E4");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_match DROP FOREIGN KEY FK_285420DCB79D50E4");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_points DROP FOREIGN KEY FK_D8E7EBBCB79D50E4");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_cup_teams_join DROP FOREIGN KEY FK_ACECFD7150BBF17");
		$this->addSql("DROP TABLE achimfritz_championship_domain_model_round");
		$this->addSql("DROP TABLE achimfritz_championship_domain_model_round_teams_join");
		$this->addSql("DROP TABLE achimfritz_championship_domain_model_koround");
		$this->addSql("DROP TABLE achimfritz_championship_domain_model_finalround");
		$this->addSql("DROP TABLE achimfritz_championship_domain_model_groupround");
		$this->addSql("DROP TABLE achimfritz_championship_domain_model_grouptablerow");
		$this->addSql("DROP TABLE achimfritz_championship_domain_model_match");
		$this->addSql("DROP TABLE achimfritz_championship_domain_model_matchparticipant");
		$this->addSql("DROP TABLE achimfritz_championship_domain_model_points");
		$this->addSql("DROP TABLE achimfritz_championship_domain_model_result");
		$this->addSql("DROP TABLE achimfritz_championship_domain_model_team");
		$this->addSql("DROP TABLE achimfritz_championship_domain_model_tip");
		$this->addSql("DROP TABLE achimfritz_championship_domain_model_user");
		$this->addSql("DROP TABLE achimfritz_championship_domain_model_cup");
		$this->addSql("DROP TABLE achimfritz_championship_domain_model_cup_teams_join");
	}
}

?>