<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130601103112 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
			// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("DROP TABLE achimfritz_championship_domain_model_grouptablerow_team_join");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_grouptablerow ADD team VARCHAR(40) DEFAULT NULL");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_grouptablerow ADD CONSTRAINT FK_789643FC4E0A61F FOREIGN KEY (team) REFERENCES achimfritz_championship_domain_model_team (persistence_object_identifier)");
		$this->addSql("CREATE INDEX IDX_789643FC4E0A61F ON achimfritz_championship_domain_model_grouptablerow (team)");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
			// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("CREATE TABLE achimfritz_championship_domain_model_grouptablerow_team_join (championship_grouptablerow VARCHAR(40) NOT NULL, championship_team VARCHAR(40) NOT NULL, INDEX IDX_A5B824D3BC373499 (championship_grouptablerow), INDEX IDX_A5B824D3E0E69356 (championship_team), PRIMARY KEY(championship_grouptablerow, championship_team)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_grouptablerow_team_join ADD CONSTRAINT FK_A5B824D3BC373499 FOREIGN KEY (championship_grouptablerow) REFERENCES achimfritz_championship_domain_model_grouptablerow (persistence_object_identifier)");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_grouptablerow_team_join ADD CONSTRAINT FK_A5B824D3E0E69356 FOREIGN KEY (championship_team) REFERENCES achimfritz_championship_domain_model_team (persistence_object_identifier)");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_grouptablerow DROP FOREIGN KEY FK_789643FC4E0A61F");
		$this->addSql("DROP INDEX IDX_789643FC4E0A61F ON achimfritz_championship_domain_model_grouptablerow");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_grouptablerow DROP team");
	}
}

?>