<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20160610074021 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
		// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("CREATE TABLE achimfritz_championship_competition_domain_model_extrapoint (persistence_object_identifier VARCHAR(40) NOT NULL, team VARCHAR(40) DEFAULT NULL, cup VARCHAR(40) DEFAULT NULL, points INT NOT NULL, INDEX IDX_7C8D0764C4E0A61F (team), INDEX IDX_7C8D0764B79D50E4 (cup), PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("ALTER TABLE achimfritz_championship_competition_domain_model_extrapoint ADD CONSTRAINT FK_7C8D0764C4E0A61F FOREIGN KEY (team) REFERENCES achimfritz_championship_competition_domain_model_team (persistence_object_identifier)");
		$this->addSql("ALTER TABLE achimfritz_championship_competition_domain_model_extrapoint ADD CONSTRAINT FK_7C8D0764B79D50E4 FOREIGN KEY (cup) REFERENCES achimfritz_championship_competition_domain_model_cup (persistence_object_identifier)");
		$this->addSql("DROP TABLE achimfritz_championship_competition_domain_model_extrapoints");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
		// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("CREATE TABLE achimfritz_championship_competition_domain_model_extrapoints (persistence_object_identifier VARCHAR(40) NOT NULL COLLATE utf8_unicode_ci, cup VARCHAR(40) DEFAULT NULL COLLATE utf8_unicode_ci, team VARCHAR(40) DEFAULT NULL COLLATE utf8_unicode_ci, points INT NOT NULL, INDEX IDX_51ADE74DC4E0A61F (team), INDEX IDX_51ADE74DB79D50E4 (cup), PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("ALTER TABLE achimfritz_championship_competition_domain_model_extrapoints ADD CONSTRAINT FK_51ADE74DB79D50E4 FOREIGN KEY (cup) REFERENCES achimfritz_championship_competition_domain_model_cup (persistence_object_identifier)");
		$this->addSql("ALTER TABLE achimfritz_championship_competition_domain_model_extrapoints ADD CONSTRAINT FK_51ADE74DC4E0A61F FOREIGN KEY (team) REFERENCES achimfritz_championship_competition_domain_model_team (persistence_object_identifier)");
		$this->addSql("DROP TABLE achimfritz_championship_competition_domain_model_extrapoint");
	}
}