<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20160427181707 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
		// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("CREATE TABLE achimfritz_championship_tip_domain_model_cupranking (persistence_object_identifier VARCHAR(40) NOT NULL, cup VARCHAR(40) DEFAULT NULL, INDEX IDX_4DD74916B79D50E4 (cup), PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("ALTER TABLE achimfritz_championship_tip_domain_model_cupranking ADD CONSTRAINT FK_4DD74916B79D50E4 FOREIGN KEY (cup) REFERENCES achimfritz_championship_competition_domain_model_cup (persistence_object_identifier)");
		$this->addSql("ALTER TABLE achimfritz_championship_tip_domain_model_cupranking ADD CONSTRAINT FK_4DD7491647A46B0A FOREIGN KEY (persistence_object_identifier) REFERENCES achimfritz_championship_tip_domain_model_ranking (persistence_object_identifier) ON DELETE CASCADE");
		$this->addSql("ALTER TABLE achimfritz_championship_tip_domain_model_ranking DROP FOREIGN KEY FK_B5BAA8C7B79D50E4");
		$this->addSql("DROP INDEX IDX_B5BAA8C7B79D50E4 ON achimfritz_championship_tip_domain_model_ranking");
		$this->addSql("ALTER TABLE achimfritz_championship_tip_domain_model_ranking ADD dtype VARCHAR(255) NOT NULL, DROP cup");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
		// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("DROP TABLE achimfritz_championship_tip_domain_model_cupranking");
		$this->addSql("ALTER TABLE achimfritz_championship_tip_domain_model_ranking ADD cup VARCHAR(40) DEFAULT NULL COLLATE utf8_unicode_ci, DROP dtype");
		$this->addSql("ALTER TABLE achimfritz_championship_tip_domain_model_ranking ADD CONSTRAINT FK_B5BAA8C7B79D50E4 FOREIGN KEY (cup) REFERENCES achimfritz_championship_competition_domain_model_cup (persistence_object_identifier)");
		$this->addSql("CREATE INDEX IDX_B5BAA8C7B79D50E4 ON achimfritz_championship_tip_domain_model_ranking (cup)");
	}
}