<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130529182605 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
			// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_round DROP FOREIGN KEY FK_97E10FED6E3D0F7D");
		$this->addSql("DROP INDEX IDX_97E10FED6E3D0F7D ON achimfritz_championship_domain_model_round");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_round DROP generalmatches");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_match ADD round VARCHAR(40) DEFAULT NULL");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_match ADD CONSTRAINT FK_285420DCC5EEEA34 FOREIGN KEY (round) REFERENCES achimfritz_championship_domain_model_round (persistence_object_identifier)");
		$this->addSql("CREATE UNIQUE INDEX UNIQ_285420DCC5EEEA34 ON achimfritz_championship_domain_model_match (round)");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
			// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_match DROP FOREIGN KEY FK_285420DCC5EEEA34");
		$this->addSql("DROP INDEX UNIQ_285420DCC5EEEA34 ON achimfritz_championship_domain_model_match");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_match DROP round");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_round ADD generalmatches VARCHAR(40) DEFAULT NULL");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_round ADD CONSTRAINT FK_97E10FED6E3D0F7D FOREIGN KEY (generalmatches) REFERENCES achimfritz_championship_domain_model_match (persistence_object_identifier)");
		$this->addSql("CREATE INDEX IDX_97E10FED6E3D0F7D ON achimfritz_championship_domain_model_round (generalmatches)");
	}
}

?>