<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140208170607 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
			// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("DROP INDEX flow_identity_achimfritz_championship_domain_model_user ON achimfritz_championship_domain_model_user");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_user ADD account VARCHAR(40) DEFAULT NULL, DROP accountidentifier, DROP authenticationprovidername, DROP credentialssource, DROP creationdate, DROP expirationdate");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_user ADD CONSTRAINT FK_EA9439FA7D3656A4 FOREIGN KEY (account) REFERENCES typo3_flow_security_account (persistence_object_identifier)");
		$this->addSql("CREATE UNIQUE INDEX UNIQ_EA9439FA7D3656A4 ON achimfritz_championship_domain_model_user (account)");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
			// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_user DROP FOREIGN KEY FK_EA9439FA7D3656A4");
		$this->addSql("DROP INDEX UNIQ_EA9439FA7D3656A4 ON achimfritz_championship_domain_model_user");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_user ADD accountidentifier VARCHAR(255) NOT NULL, ADD authenticationprovidername VARCHAR(255) NOT NULL, ADD credentialssource VARCHAR(255) DEFAULT NULL, ADD creationdate DATETIME NOT NULL, ADD expirationdate DATETIME DEFAULT NULL, DROP account");
		$this->addSql("CREATE UNIQUE INDEX flow_identity_achimfritz_championship_domain_model_user ON achimfritz_championship_domain_model_user (accountidentifier, authenticationprovidername)");
	}
}

?>