<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130731211100 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
			// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("CREATE TABLE achimfritz_championship_domain_model_teamsoftwomatchesmatch (persistence_object_identifier VARCHAR(40) NOT NULL, hostmatch VARCHAR(40) DEFAULT NULL, guestmatch VARCHAR(40) DEFAULT NULL, UNIQUE INDEX UNIQ_7BB97C90F933327C (hostmatch), UNIQUE INDEX UNIQ_7BB97C903C4E843 (guestmatch), PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_teamsoftwomatchesmatch ADD CONSTRAINT FK_7BB97C90F933327C FOREIGN KEY (hostmatch) REFERENCES achimfritz_championship_domain_model_komatch (persistence_object_identifier)");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_teamsoftwomatchesmatch ADD CONSTRAINT FK_7BB97C903C4E843 FOREIGN KEY (guestmatch) REFERENCES achimfritz_championship_domain_model_komatch (persistence_object_identifier)");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_teamsoftwomatchesmatch ADD CONSTRAINT FK_7BB97C9047A46B0A FOREIGN KEY (persistence_object_identifier) REFERENCES achimfritz_championship_domain_model_match (persistence_object_identifier) ON DELETE CASCADE");
		$this->addSql("DROP TABLE achimfritz_championship_domain_model_winnersoftwomatchesmatch");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
			// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("CREATE TABLE achimfritz_championship_domain_model_winnersoftwomatchesmatch (persistence_object_identifier VARCHAR(40) NOT NULL, guestmatch VARCHAR(40) DEFAULT NULL, hostmatch VARCHAR(40) DEFAULT NULL, UNIQUE INDEX UNIQ_26E95E79F933327C (hostmatch), UNIQUE INDEX UNIQ_26E95E793C4E843 (guestmatch), PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_winnersoftwomatchesmatch ADD CONSTRAINT FK_26E95E793C4E843 FOREIGN KEY (guestmatch) REFERENCES achimfritz_championship_domain_model_komatch (persistence_object_identifier)");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_winnersoftwomatchesmatch ADD CONSTRAINT FK_26E95E7947A46B0A FOREIGN KEY (persistence_object_identifier) REFERENCES achimfritz_championship_domain_model_match (persistence_object_identifier) ON DELETE CASCADE");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_winnersoftwomatchesmatch ADD CONSTRAINT FK_26E95E79F933327C FOREIGN KEY (hostmatch) REFERENCES achimfritz_championship_domain_model_komatch (persistence_object_identifier)");
		$this->addSql("DROP TABLE achimfritz_championship_domain_model_teamsoftwomatchesmatch");
	}
}

?>