<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130524202427 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
			// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("CREATE TABLE achimfritz_championship_domain_model_match (persistence_object_identifier VARCHAR(40) NOT NULL, hostteam VARCHAR(40) DEFAULT NULL, guastteam VARCHAR(40) DEFAULT NULL, INDEX IDX_285420DC7F921808 (hostteam), INDEX IDX_285420DC733A6005 (guastteam), PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_match ADD CONSTRAINT FK_285420DC7F921808 FOREIGN KEY (hostteam) REFERENCES achimfritz_championship_domain_model_team (persistence_object_identifier)");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_match ADD CONSTRAINT FK_285420DC733A6005 FOREIGN KEY (guastteam) REFERENCES achimfritz_championship_domain_model_team (persistence_object_identifier)");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
			// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("DROP TABLE achimfritz_championship_domain_model_match");
	}
}

?>