<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140208144416 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
			// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_password DROP FOREIGN KEY FK_42C52007D3656A4");
		$this->addSql("DROP INDEX UNIQ_42C52007D3656A4 ON achimfritz_championship_domain_model_password");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_password CHANGE account user VARCHAR(40) DEFAULT NULL");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_password ADD CONSTRAINT FK_42C52008D93D649 FOREIGN KEY (user) REFERENCES achimfritz_championship_domain_model_user (persistence_object_identifier)");
		$this->addSql("CREATE UNIQUE INDEX UNIQ_42C52008D93D649 ON achimfritz_championship_domain_model_password (user)");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_user DROP FOREIGN KEY FK_EA9439FA7D3656A4");
		$this->addSql("DROP INDEX UNIQ_EA9439FA7D3656A4 ON achimfritz_championship_domain_model_user");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_user ADD accountidentifier VARCHAR(255) NOT NULL, ADD authenticationprovidername VARCHAR(255) NOT NULL, ADD credentialssource VARCHAR(255) DEFAULT NULL, ADD creationdate DATETIME NOT NULL, ADD expirationdate DATETIME DEFAULT NULL, ADD email VARCHAR(255) NOT NULL, DROP account");
		$this->addSql("CREATE UNIQUE INDEX flow_identity_achimfritz_championship_domain_model_user ON achimfritz_championship_domain_model_user (accountidentifier, authenticationprovidername)");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
			// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_password DROP FOREIGN KEY FK_42C52008D93D649");
		$this->addSql("DROP INDEX UNIQ_42C52008D93D649 ON achimfritz_championship_domain_model_password");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_password CHANGE user account VARCHAR(40) DEFAULT NULL");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_password ADD CONSTRAINT FK_42C52007D3656A4 FOREIGN KEY (account) REFERENCES typo3_flow_security_account (persistence_object_identifier)");
		$this->addSql("CREATE UNIQUE INDEX UNIQ_42C52007D3656A4 ON achimfritz_championship_domain_model_password (account)");
		$this->addSql("DROP INDEX flow_identity_achimfritz_championship_domain_model_user ON achimfritz_championship_domain_model_user");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_user ADD account VARCHAR(40) DEFAULT NULL, DROP accountidentifier, DROP authenticationprovidername, DROP credentialssource, DROP creationdate, DROP expirationdate, DROP email");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_user ADD CONSTRAINT FK_EA9439FA7D3656A4 FOREIGN KEY (account) REFERENCES typo3_flow_security_account (persistence_object_identifier)");
		$this->addSql("CREATE UNIQUE INDEX UNIQ_EA9439FA7D3656A4 ON achimfritz_championship_domain_model_user (account)");
	}
}

?>