<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20131007174148 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
			// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_points DROP FOREIGN KEY FK_D8E7EBBCC4E0A61F");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_points DROP FOREIGN KEY FK_D8E7EBBCDFBDA53F");
		$this->addSql("DROP INDEX IDX_D8E7EBBCDFBDA53F ON achimfritz_championship_domain_model_points");
		$this->addSql("DROP INDEX IDX_D8E7EBBCC4E0A61F ON achimfritz_championship_domain_model_points");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_points DROP team, DROP generalmatch");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
			// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_points ADD team VARCHAR(40) DEFAULT NULL, ADD generalmatch VARCHAR(40) DEFAULT NULL");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_points ADD CONSTRAINT FK_D8E7EBBCC4E0A61F FOREIGN KEY (team) REFERENCES achimfritz_championship_domain_model_team (persistence_object_identifier)");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_points ADD CONSTRAINT FK_D8E7EBBCDFBDA53F FOREIGN KEY (generalmatch) REFERENCES achimfritz_championship_domain_model_match (persistence_object_identifier)");
		$this->addSql("CREATE INDEX IDX_D8E7EBBCDFBDA53F ON achimfritz_championship_domain_model_points (generalmatch)");
		$this->addSql("CREATE INDEX IDX_D8E7EBBCC4E0A61F ON achimfritz_championship_domain_model_points (team)");
	}
}

?>