<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130728150011 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
			// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("CREATE TABLE achimfritz_championship_domain_model_crossgroupround (persistence_object_identifier VARCHAR(40) NOT NULL, PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("CREATE TABLE achimfritz_championship_domain_model_winneroftwomatchesround (persistence_object_identifier VARCHAR(40) NOT NULL, parentround VARCHAR(40) DEFAULT NULL, INDEX IDX_BA8D548DA528AC9B (parentround), PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_crossgroupround ADD CONSTRAINT FK_7ED2103447A46B0A FOREIGN KEY (persistence_object_identifier) REFERENCES achimfritz_championship_domain_model_round (persistence_object_identifier) ON DELETE CASCADE");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_winneroftwomatchesround ADD CONSTRAINT FK_BA8D548DA528AC9B FOREIGN KEY (parentround) REFERENCES achimfritz_championship_domain_model_koround (persistence_object_identifier)");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_winneroftwomatchesround ADD CONSTRAINT FK_BA8D548D47A46B0A FOREIGN KEY (persistence_object_identifier) REFERENCES achimfritz_championship_domain_model_round (persistence_object_identifier) ON DELETE CASCADE");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_koround DROP FOREIGN KEY FK_6E295D69A528AC9B");
		$this->addSql("DROP INDEX IDX_6E295D69A528AC9B ON achimfritz_championship_domain_model_koround");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_koround DROP parentround");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
			// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("DROP TABLE achimfritz_championship_domain_model_crossgroupround");
		$this->addSql("DROP TABLE achimfritz_championship_domain_model_winneroftwomatchesround");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_koround ADD parentround VARCHAR(40) DEFAULT NULL");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_koround ADD CONSTRAINT FK_6E295D69A528AC9B FOREIGN KEY (parentround) REFERENCES achimfritz_championship_domain_model_koround (persistence_object_identifier)");
		$this->addSql("CREATE INDEX IDX_6E295D69A528AC9B ON achimfritz_championship_domain_model_koround (parentround)");
	}
}

?>