<?php
namespace Neos\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20160424113054 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
		// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("DROP INDEX flow_identity_achimfritz_championship_tip_domain_model_tipgroup ON achimfritz_championship_user_domain_model_tipgroup");
		$this->addSql("CREATE UNIQUE INDEX flow_identity_achimfritz_championship_user_domain_model_t_1420c ON achimfritz_championship_user_domain_model_tipgroup (name)");
		$this->addSql("ALTER TABLE achimfritz_championship_user_domain_model_user_tipgroups_join DROP FOREIGN KEY FK_318E50795D3384B7");
		$this->addSql("DROP INDEX idx_42d6da98ba56f723 ON achimfritz_championship_user_domain_model_user_tipgroups_join");
		$this->addSql("CREATE INDEX IDX_42D6DA98135B132C ON achimfritz_championship_user_domain_model_user_tipgroups_join (user_tipgroup)");
		$this->addSql("ALTER TABLE achimfritz_championship_user_domain_model_user_tipgroups_join ADD CONSTRAINT FK_318E50795D3384B7 FOREIGN KEY (user_tipgroup) REFERENCES achimfritz_championship_user_domain_model_tipgroup (persistence_object_identifier)");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
		// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("DROP INDEX flow_identity_achimfritz_championship_user_domain_model_t_1420c ON achimfritz_championship_user_domain_model_tipgroup");
		$this->addSql("CREATE UNIQUE INDEX flow_identity_achimfritz_championship_tip_domain_model_tipgroup ON achimfritz_championship_user_domain_model_tipgroup (name)");
		$this->addSql("ALTER TABLE achimfritz_championship_user_domain_model_user_tipgroups_join DROP FOREIGN KEY FK_42D6DA98135B132C");
		$this->addSql("DROP INDEX idx_42d6da98135b132c ON achimfritz_championship_user_domain_model_user_tipgroups_join");
		$this->addSql("CREATE INDEX IDX_42D6DA98BA56F723 ON achimfritz_championship_user_domain_model_user_tipgroups_join (user_tipgroup)");
		$this->addSql("ALTER TABLE achimfritz_championship_user_domain_model_user_tipgroups_join ADD CONSTRAINT FK_42D6DA98135B132C FOREIGN KEY (user_tipgroup) REFERENCES achimfritz_championship_user_domain_model_tipgroup (persistence_object_identifier)");
	}
}