<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130525154253 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
			// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("CREATE TABLE achimfritz_championship_domain_model_cup (persistence_object_identifier VARCHAR(40) NOT NULL, PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("CREATE TABLE achimfritz_championship_domain_model_cup_teams_join (championship_cup VARCHAR(40) NOT NULL, championship_team VARCHAR(40) NOT NULL, INDEX IDX_ACECFD7150BBF17 (championship_cup), INDEX IDX_ACECFD71E0E69356 (championship_team), PRIMARY KEY(championship_cup, championship_team)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("CREATE TABLE achimfritz_championship_domain_model_cup_matchtypes_join (championship_cup VARCHAR(40) NOT NULL, championship_matchtype VARCHAR(40) NOT NULL, INDEX IDX_7E4129AE50BBF17 (championship_cup), INDEX IDX_7E4129AEA28840B2 (championship_matchtype), PRIMARY KEY(championship_cup, championship_matchtype)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("CREATE TABLE achimfritz_championship_domain_model_cupmatch (persistence_object_identifier VARCHAR(40) NOT NULL, hostteam VARCHAR(40) DEFAULT NULL, guestteam VARCHAR(40) DEFAULT NULL, matchtype VARCHAR(40) DEFAULT NULL, cup VARCHAR(40) DEFAULT NULL, result VARCHAR(40) DEFAULT NULL, startdate DATETIME NOT NULL, INDEX IDX_3A3ACB17F921808 (hostteam), INDEX IDX_3A3ACB187754416 (guestteam), INDEX IDX_3A3ACB1C5FBEF0D (matchtype), INDEX IDX_3A3ACB1B79D50E4 (cup), UNIQUE INDEX UNIQ_3A3ACB1136AC113 (result), PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("CREATE TABLE achimfritz_championship_domain_model_points (persistence_object_identifier VARCHAR(40) NOT NULL, cup VARCHAR(40) DEFAULT NULL, cupmatch VARCHAR(40) DEFAULT NULL, user VARCHAR(40) DEFAULT NULL, matchtype VARCHAR(40) DEFAULT NULL, team VARCHAR(40) DEFAULT NULL, points INT NOT NULL, INDEX IDX_D8E7EBBCB79D50E4 (cup), INDEX IDX_D8E7EBBC324DB864 (cupmatch), INDEX IDX_D8E7EBBC8D93D649 (user), INDEX IDX_D8E7EBBCC5FBEF0D (matchtype), INDEX IDX_D8E7EBBCC4E0A61F (team), PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("CREATE TABLE achimfritz_championship_domain_model_tip (persistence_object_identifier VARCHAR(40) NOT NULL, user VARCHAR(40) DEFAULT NULL, cupmatch VARCHAR(40) DEFAULT NULL, restult VARCHAR(40) DEFAULT NULL, INDEX IDX_9226C7D78D93D649 (user), INDEX IDX_9226C7D7324DB864 (cupmatch), UNIQUE INDEX UNIQ_9226C7D728971674 (restult), PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_cup_teams_join ADD CONSTRAINT FK_ACECFD7150BBF17 FOREIGN KEY (championship_cup) REFERENCES achimfritz_championship_domain_model_cup (persistence_object_identifier)");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_cup_teams_join ADD CONSTRAINT FK_ACECFD71E0E69356 FOREIGN KEY (championship_team) REFERENCES achimfritz_championship_domain_model_team (persistence_object_identifier)");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_cup_matchtypes_join ADD CONSTRAINT FK_7E4129AE50BBF17 FOREIGN KEY (championship_cup) REFERENCES achimfritz_championship_domain_model_cup (persistence_object_identifier)");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_cup_matchtypes_join ADD CONSTRAINT FK_7E4129AEA28840B2 FOREIGN KEY (championship_matchtype) REFERENCES achimfritz_championship_domain_model_matchtype (persistence_object_identifier)");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_cupmatch ADD CONSTRAINT FK_3A3ACB17F921808 FOREIGN KEY (hostteam) REFERENCES achimfritz_championship_domain_model_team (persistence_object_identifier)");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_cupmatch ADD CONSTRAINT FK_3A3ACB187754416 FOREIGN KEY (guestteam) REFERENCES achimfritz_championship_domain_model_team (persistence_object_identifier)");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_cupmatch ADD CONSTRAINT FK_3A3ACB1C5FBEF0D FOREIGN KEY (matchtype) REFERENCES achimfritz_championship_domain_model_matchtype (persistence_object_identifier)");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_cupmatch ADD CONSTRAINT FK_3A3ACB1B79D50E4 FOREIGN KEY (cup) REFERENCES achimfritz_championship_domain_model_cup (persistence_object_identifier)");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_cupmatch ADD CONSTRAINT FK_3A3ACB1136AC113 FOREIGN KEY (result) REFERENCES achimfritz_championship_domain_model_result (persistence_object_identifier)");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_points ADD CONSTRAINT FK_D8E7EBBCB79D50E4 FOREIGN KEY (cup) REFERENCES achimfritz_championship_domain_model_cup (persistence_object_identifier)");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_points ADD CONSTRAINT FK_D8E7EBBC324DB864 FOREIGN KEY (cupmatch) REFERENCES achimfritz_championship_domain_model_cupmatch (persistence_object_identifier)");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_points ADD CONSTRAINT FK_D8E7EBBC8D93D649 FOREIGN KEY (user) REFERENCES achimfritz_championship_domain_model_user (persistence_object_identifier)");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_points ADD CONSTRAINT FK_D8E7EBBCC5FBEF0D FOREIGN KEY (matchtype) REFERENCES achimfritz_championship_domain_model_matchtype (persistence_object_identifier)");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_points ADD CONSTRAINT FK_D8E7EBBCC4E0A61F FOREIGN KEY (team) REFERENCES achimfritz_championship_domain_model_team (persistence_object_identifier)");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_tip ADD CONSTRAINT FK_9226C7D78D93D649 FOREIGN KEY (user) REFERENCES achimfritz_championship_domain_model_user (persistence_object_identifier)");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_tip ADD CONSTRAINT FK_9226C7D7324DB864 FOREIGN KEY (cupmatch) REFERENCES achimfritz_championship_domain_model_cupmatch (persistence_object_identifier)");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_tip ADD CONSTRAINT FK_9226C7D728971674 FOREIGN KEY (restult) REFERENCES achimfritz_championship_domain_model_result (persistence_object_identifier)");
		$this->addSql("DROP TABLE achimfritz_championship_domain_model_match");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_team ADD short VARCHAR(255) NOT NULL");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
			// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_cup_teams_join DROP FOREIGN KEY FK_ACECFD7150BBF17");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_cup_matchtypes_join DROP FOREIGN KEY FK_7E4129AE50BBF17");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_cupmatch DROP FOREIGN KEY FK_3A3ACB1B79D50E4");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_points DROP FOREIGN KEY FK_D8E7EBBCB79D50E4");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_points DROP FOREIGN KEY FK_D8E7EBBC324DB864");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_tip DROP FOREIGN KEY FK_9226C7D7324DB864");
		$this->addSql("CREATE TABLE achimfritz_championship_domain_model_match (persistence_object_identifier VARCHAR(40) NOT NULL, guastteam VARCHAR(40) DEFAULT NULL, hostteam VARCHAR(40) DEFAULT NULL, INDEX IDX_285420DC7F921808 (hostteam), INDEX IDX_285420DC733A6005 (guastteam), PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_match ADD CONSTRAINT FK_285420DC733A6005 FOREIGN KEY (guastteam) REFERENCES achimfritz_championship_domain_model_team (persistence_object_identifier)");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_match ADD CONSTRAINT FK_285420DC7F921808 FOREIGN KEY (hostteam) REFERENCES achimfritz_championship_domain_model_team (persistence_object_identifier)");
		$this->addSql("DROP TABLE achimfritz_championship_domain_model_cup");
		$this->addSql("DROP TABLE achimfritz_championship_domain_model_cup_teams_join");
		$this->addSql("DROP TABLE achimfritz_championship_domain_model_cup_matchtypes_join");
		$this->addSql("DROP TABLE achimfritz_championship_domain_model_cupmatch");
		$this->addSql("DROP TABLE achimfritz_championship_domain_model_points");
		$this->addSql("DROP TABLE achimfritz_championship_domain_model_tip");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_team DROP short");
	}
}

?>