<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20160523165809 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
		// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("CREATE TABLE achimfritz_championship_competition_domain_model_crossgro_96a78 (persistence_object_identifier VARCHAR(40) NOT NULL, PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("CREATE TABLE achimfritz_championship_competition_96a78_guestgrouprounds_join (competition_crossgroupwiththirdsmatch VARCHAR(40) NOT NULL, competition_groupround VARCHAR(40) NOT NULL, INDEX IDX_DABC0273383A353A (competition_crossgroupwiththirdsmatch), INDEX IDX_DABC027312862167 (competition_groupround), PRIMARY KEY(competition_crossgroupwiththirdsmatch, competition_groupround)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("ALTER TABLE achimfritz_championship_competition_domain_model_crossgro_96a78 ADD CONSTRAINT FK_1DC9F0E347A46B0A FOREIGN KEY (persistence_object_identifier) REFERENCES achimfritz_championship_competition_domain_model_match (persistence_object_identifier) ON DELETE CASCADE");
		$this->addSql("ALTER TABLE achimfritz_championship_competition_96a78_guestgrouprounds_join ADD CONSTRAINT FK_DABC0273383A353A FOREIGN KEY (competition_crossgroupwiththirdsmatch) REFERENCES achimfritz_championship_competition_domain_model_crossgro_96a78 (persistence_object_identifier)");
		$this->addSql("ALTER TABLE achimfritz_championship_competition_96a78_guestgrouprounds_join ADD CONSTRAINT FK_DABC027312862167 FOREIGN KEY (competition_groupround) REFERENCES achimfritz_championship_competition_domain_model_groupround (persistence_object_identifier)");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
		// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("ALTER TABLE achimfritz_championship_competition_96a78_guestgrouprounds_join DROP FOREIGN KEY FK_DABC0273383A353A");
		$this->addSql("DROP TABLE achimfritz_championship_competition_domain_model_crossgro_96a78");
		$this->addSql("DROP TABLE achimfritz_championship_competition_96a78_guestgrouprounds_join");
	}
}