<?php
namespace Neos\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20160406184717 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
		// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("ALTER TABLE achimfritz_championship_competition_domain_model_round DROP FOREIGN KEY FK_97E10FEDB79D50E4");
		$this->addSql("DROP INDEX idx_97e10fedb79d50e4 ON achimfritz_championship_competition_domain_model_round");
		$this->addSql("CREATE INDEX IDX_362D347CB79D50E4 ON achimfritz_championship_competition_domain_model_round (cup)");
		$this->addSql("ALTER TABLE achimfritz_championship_competition_domain_model_round ADD CONSTRAINT FK_97E10FEDB79D50E4 FOREIGN KEY (cup) REFERENCES achimfritz_championship_competition_domain_model_cup (persistence_object_identifier)");
		$this->addSql("ALTER TABLE achimfritz_championship_competition_domain_mod_5fbbe_teams_join DROP FOREIGN KEY FK_B4C549D4CACA1535");
		$this->addSql("ALTER TABLE achimfritz_championship_competition_domain_mod_5fbbe_teams_join DROP FOREIGN KEY FK_B4C549D4E0E69356");
		$this->addSql("DROP INDEX idx_b4c549d4caca1535 ON achimfritz_championship_competition_domain_mod_5fbbe_teams_join");
		$this->addSql("CREATE INDEX IDX_14B10C513659D8E2 ON achimfritz_championship_competition_domain_mod_5fbbe_teams_join (competition_round)");
		$this->addSql("DROP INDEX idx_b4c549d4e0e69356 ON achimfritz_championship_competition_domain_mod_5fbbe_teams_join");
		$this->addSql("CREATE INDEX IDX_14B10C51CAA3380D ON achimfritz_championship_competition_domain_mod_5fbbe_teams_join (competition_team)");
		$this->addSql("ALTER TABLE achimfritz_championship_competition_domain_mod_5fbbe_teams_join ADD CONSTRAINT FK_B4C549D4CACA1535 FOREIGN KEY (competition_round) REFERENCES achimfritz_championship_competition_domain_model_round (persistence_object_identifier)");
		$this->addSql("ALTER TABLE achimfritz_championship_competition_domain_mod_5fbbe_teams_join ADD CONSTRAINT FK_B4C549D4E0E69356 FOREIGN KEY (competition_team) REFERENCES achimfritz_championship_competition_domain_model_team (persistence_object_identifier)");
		$this->addSql("ALTER TABLE achimfritz_championship_competition_domain_model_childkoround DROP FOREIGN KEY FK_E553D847A528AC9B");
		$this->addSql("DROP INDEX idx_e553d847a528ac9b ON achimfritz_championship_competition_domain_model_childkoround");
		$this->addSql("CREATE INDEX IDX_1B63291BA528AC9B ON achimfritz_championship_competition_domain_model_childkoround (parentround)");
		$this->addSql("ALTER TABLE achimfritz_championship_competition_domain_model_childkoround ADD CONSTRAINT FK_E553D847A528AC9B FOREIGN KEY (parentround) REFERENCES achimfritz_championship_competition_domain_model_koround (persistence_object_identifier)");
		$this->addSql("DROP INDEX flow_identity_achimfritz_championship_domain_model_cup ON achimfritz_championship_competition_domain_model_cup");
		$this->addSql("CREATE UNIQUE INDEX flow_identity_achimfritz_championship_competition_domain__fd683 ON achimfritz_championship_competition_domain_model_cup (name)");
		$this->addSql("ALTER TABLE achimfritz_championship_competition_domain_model_cup_teams_join DROP FOREIGN KEY FK_ACECFD7150BBF17");
		$this->addSql("ALTER TABLE achimfritz_championship_competition_domain_model_cup_teams_join DROP FOREIGN KEY FK_ACECFD71E0E69356");
		$this->addSql("DROP INDEX idx_acecfd7150bbf17 ON achimfritz_championship_competition_domain_model_cup_teams_join");
		$this->addSql("CREATE INDEX IDX_7058D3932F8B70EC ON achimfritz_championship_competition_domain_model_cup_teams_join (competition_cup)");
		$this->addSql("DROP INDEX idx_acecfd71e0e69356 ON achimfritz_championship_competition_domain_model_cup_teams_join");
		$this->addSql("CREATE INDEX IDX_7058D393CAA3380D ON achimfritz_championship_competition_domain_model_cup_teams_join (competition_team)");
		$this->addSql("ALTER TABLE achimfritz_championship_competition_domain_model_cup_teams_join ADD CONSTRAINT FK_ACECFD7150BBF17 FOREIGN KEY (competition_cup) REFERENCES achimfritz_championship_competition_domain_model_cup (persistence_object_identifier)");
		$this->addSql("ALTER TABLE achimfritz_championship_competition_domain_model_cup_teams_join ADD CONSTRAINT FK_ACECFD71E0E69356 FOREIGN KEY (competition_team) REFERENCES achimfritz_championship_competition_domain_model_team (persistence_object_identifier)");
		$this->addSql("ALTER TABLE achimfritz_championship_competition_domain_model_grouptablerow DROP FOREIGN KEY FK_789643FB191C15F");
		$this->addSql("ALTER TABLE achimfritz_championship_competition_domain_model_grouptablerow DROP FOREIGN KEY FK_789643FC4E0A61F");
		$this->addSql("DROP INDEX idx_789643fc4e0a61f ON achimfritz_championship_competition_domain_model_grouptablerow");
		$this->addSql("CREATE INDEX IDX_65AA4911C4E0A61F ON achimfritz_championship_competition_domain_model_grouptablerow (team)");
		$this->addSql("DROP INDEX idx_789643fb191c15f ON achimfritz_championship_competition_domain_model_grouptablerow");
		$this->addSql("CREATE INDEX IDX_65AA4911B191C15F ON achimfritz_championship_competition_domain_model_grouptablerow (groupround)");
		$this->addSql("ALTER TABLE achimfritz_championship_competition_domain_model_grouptablerow ADD CONSTRAINT FK_789643FB191C15F FOREIGN KEY (groupround) REFERENCES achimfritz_championship_competition_domain_model_groupround (persistence_object_identifier)");
		$this->addSql("ALTER TABLE achimfritz_championship_competition_domain_model_grouptablerow ADD CONSTRAINT FK_789643FC4E0A61F FOREIGN KEY (team) REFERENCES achimfritz_championship_competition_domain_model_team (persistence_object_identifier)");
		$this->addSql("DROP INDEX flow_identity_achimfritz_championship_domain_model_team ON achimfritz_championship_competition_domain_model_team");
		$this->addSql("CREATE UNIQUE INDEX flow_identity_achimfritz_championship_competition_domain__419a2 ON achimfritz_championship_competition_domain_model_team (name)");
		$this->addSql("ALTER TABLE achimfritz_championship_competition_domain_model_match DROP FOREIGN KEY FK_285420DC136AC113");
		$this->addSql("ALTER TABLE achimfritz_championship_competition_domain_model_match DROP FOREIGN KEY FK_285420DC7F921808");
		$this->addSql("ALTER TABLE achimfritz_championship_competition_domain_model_match DROP FOREIGN KEY FK_285420DC87754416");
		$this->addSql("ALTER TABLE achimfritz_championship_competition_domain_model_match DROP FOREIGN KEY FK_285420DCB79D50E4");
		$this->addSql("ALTER TABLE achimfritz_championship_competition_domain_model_match DROP FOREIGN KEY FK_285420DCC5EEEA34");
		$this->addSql("DROP INDEX idx_285420dc7f921808 ON achimfritz_championship_competition_domain_model_match");
		$this->addSql("CREATE INDEX IDX_89981B4D7F921808 ON achimfritz_championship_competition_domain_model_match (hostteam)");
		$this->addSql("DROP INDEX idx_285420dc87754416 ON achimfritz_championship_competition_domain_model_match");
		$this->addSql("CREATE INDEX IDX_89981B4D87754416 ON achimfritz_championship_competition_domain_model_match (guestteam)");
		$this->addSql("DROP INDEX idx_285420dcb79d50e4 ON achimfritz_championship_competition_domain_model_match");
		$this->addSql("CREATE INDEX IDX_89981B4DB79D50E4 ON achimfritz_championship_competition_domain_model_match (cup)");
		$this->addSql("DROP INDEX idx_285420dcc5eeea34 ON achimfritz_championship_competition_domain_model_match");
		$this->addSql("CREATE INDEX IDX_89981B4DC5EEEA34 ON achimfritz_championship_competition_domain_model_match (round)");
		$this->addSql("DROP INDEX uniq_285420dc136ac113 ON achimfritz_championship_competition_domain_model_match");
		$this->addSql("CREATE UNIQUE INDEX UNIQ_89981B4D136AC113 ON achimfritz_championship_competition_domain_model_match (result)");
		$this->addSql("ALTER TABLE achimfritz_championship_competition_domain_model_match ADD CONSTRAINT FK_285420DC136AC113 FOREIGN KEY (result) REFERENCES achimfritz_championship_competition_domain_model_result (persistence_object_identifier)");
		$this->addSql("ALTER TABLE achimfritz_championship_competition_domain_model_match ADD CONSTRAINT FK_285420DC7F921808 FOREIGN KEY (hostteam) REFERENCES achimfritz_championship_competition_domain_model_team (persistence_object_identifier)");
		$this->addSql("ALTER TABLE achimfritz_championship_competition_domain_model_match ADD CONSTRAINT FK_285420DC87754416 FOREIGN KEY (guestteam) REFERENCES achimfritz_championship_competition_domain_model_team (persistence_object_identifier)");
		$this->addSql("ALTER TABLE achimfritz_championship_competition_domain_model_match ADD CONSTRAINT FK_285420DCB79D50E4 FOREIGN KEY (cup) REFERENCES achimfritz_championship_competition_domain_model_cup (persistence_object_identifier)");
		$this->addSql("ALTER TABLE achimfritz_championship_competition_domain_model_match ADD CONSTRAINT FK_285420DCC5EEEA34 FOREIGN KEY (round) REFERENCES achimfritz_championship_competition_domain_model_round (persistence_object_identifier)");
		$this->addSql("ALTER TABLE achimfritz_championship_competition_domain_model_crossgro_ce83d DROP FOREIGN KEY FK_C1673F053CC82627");
		$this->addSql("ALTER TABLE achimfritz_championship_competition_domain_model_crossgro_ce83d DROP FOREIGN KEY FK_C1673F058883CEF");
		$this->addSql("DROP INDEX idx_c1673f058883cef ON achimfritz_championship_competition_domain_model_crossgro_ce83d");
		$this->addSql("CREATE INDEX IDX_D30E4A218883CEF ON achimfritz_championship_competition_domain_model_crossgro_ce83d (hostgroupround)");
		$this->addSql("DROP INDEX idx_c1673f053cc82627 ON achimfritz_championship_competition_domain_model_crossgro_ce83d");
		$this->addSql("CREATE INDEX IDX_D30E4A213CC82627 ON achimfritz_championship_competition_domain_model_crossgro_ce83d (guestgroupround)");
		$this->addSql("ALTER TABLE achimfritz_championship_competition_domain_model_crossgro_ce83d ADD CONSTRAINT FK_C1673F053CC82627 FOREIGN KEY (guestgroupround) REFERENCES achimfritz_championship_competition_domain_model_groupround (persistence_object_identifier)");
		$this->addSql("ALTER TABLE achimfritz_championship_competition_domain_model_crossgro_ce83d ADD CONSTRAINT FK_C1673F058883CEF FOREIGN KEY (hostgroupround) REFERENCES achimfritz_championship_competition_domain_model_groupround (persistence_object_identifier)");
		$this->addSql("ALTER TABLE achimfritz_championship_competition_domain_model_teamsoft_a6728 DROP FOREIGN KEY FK_7BB97C903C4E843");
		$this->addSql("ALTER TABLE achimfritz_championship_competition_domain_model_teamsoft_a6728 DROP FOREIGN KEY FK_7BB97C90F933327C");
		$this->addSql("DROP INDEX idx_7bb97c90f933327c ON achimfritz_championship_competition_domain_model_teamsoft_a6728");
		$this->addSql("CREATE INDEX IDX_F9A68DAEF933327C ON achimfritz_championship_competition_domain_model_teamsoft_a6728 (hostmatch)");
		$this->addSql("DROP INDEX idx_7bb97c903c4e843 ON achimfritz_championship_competition_domain_model_teamsoft_a6728");
		$this->addSql("CREATE INDEX IDX_F9A68DAE3C4E843 ON achimfritz_championship_competition_domain_model_teamsoft_a6728 (guestmatch)");
		$this->addSql("ALTER TABLE achimfritz_championship_competition_domain_model_teamsoft_a6728 ADD CONSTRAINT FK_7BB97C903C4E843 FOREIGN KEY (guestmatch) REFERENCES achimfritz_championship_competition_domain_model_komatch (persistence_object_identifier)");
		$this->addSql("ALTER TABLE achimfritz_championship_competition_domain_model_teamsoft_a6728 ADD CONSTRAINT FK_7BB97C90F933327C FOREIGN KEY (hostmatch) REFERENCES achimfritz_championship_competition_domain_model_komatch (persistence_object_identifier)");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
		// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("ALTER TABLE achimfritz_championship_competition_domain_mod_5fbbe_teams_join DROP FOREIGN KEY FK_14B10C513659D8E2");
		$this->addSql("ALTER TABLE achimfritz_championship_competition_domain_mod_5fbbe_teams_join DROP FOREIGN KEY FK_14B10C51CAA3380D");
		$this->addSql("DROP INDEX idx_14b10c513659d8e2 ON achimfritz_championship_competition_domain_mod_5fbbe_teams_join");
		$this->addSql("CREATE INDEX IDX_B4C549D4CACA1535 ON achimfritz_championship_competition_domain_mod_5fbbe_teams_join (competition_round)");
		$this->addSql("DROP INDEX idx_14b10c51caa3380d ON achimfritz_championship_competition_domain_mod_5fbbe_teams_join");
		$this->addSql("CREATE INDEX IDX_B4C549D4E0E69356 ON achimfritz_championship_competition_domain_mod_5fbbe_teams_join (competition_team)");
		$this->addSql("ALTER TABLE achimfritz_championship_competition_domain_mod_5fbbe_teams_join ADD CONSTRAINT FK_14B10C513659D8E2 FOREIGN KEY (competition_round) REFERENCES achimfritz_championship_competition_domain_model_round (persistence_object_identifier)");
		$this->addSql("ALTER TABLE achimfritz_championship_competition_domain_mod_5fbbe_teams_join ADD CONSTRAINT FK_14B10C51CAA3380D FOREIGN KEY (competition_team) REFERENCES achimfritz_championship_competition_domain_model_team (persistence_object_identifier)");
		$this->addSql("ALTER TABLE achimfritz_championship_competition_domain_model_childkoround DROP FOREIGN KEY FK_1B63291BA528AC9B");
		$this->addSql("DROP INDEX idx_1b63291ba528ac9b ON achimfritz_championship_competition_domain_model_childkoround");
		$this->addSql("CREATE INDEX IDX_E553D847A528AC9B ON achimfritz_championship_competition_domain_model_childkoround (parentround)");
		$this->addSql("ALTER TABLE achimfritz_championship_competition_domain_model_childkoround ADD CONSTRAINT FK_1B63291BA528AC9B FOREIGN KEY (parentround) REFERENCES achimfritz_championship_competition_domain_model_koround (persistence_object_identifier)");
		$this->addSql("ALTER TABLE achimfritz_championship_competition_domain_model_crossgro_ce83d DROP FOREIGN KEY FK_D30E4A218883CEF");
		$this->addSql("ALTER TABLE achimfritz_championship_competition_domain_model_crossgro_ce83d DROP FOREIGN KEY FK_D30E4A213CC82627");
		$this->addSql("DROP INDEX idx_d30e4a218883cef ON achimfritz_championship_competition_domain_model_crossgro_ce83d");
		$this->addSql("CREATE INDEX IDX_C1673F058883CEF ON achimfritz_championship_competition_domain_model_crossgro_ce83d (hostgroupround)");
		$this->addSql("DROP INDEX idx_d30e4a213cc82627 ON achimfritz_championship_competition_domain_model_crossgro_ce83d");
		$this->addSql("CREATE INDEX IDX_C1673F053CC82627 ON achimfritz_championship_competition_domain_model_crossgro_ce83d (guestgroupround)");
		$this->addSql("ALTER TABLE achimfritz_championship_competition_domain_model_crossgro_ce83d ADD CONSTRAINT FK_D30E4A218883CEF FOREIGN KEY (hostgroupround) REFERENCES achimfritz_championship_competition_domain_model_groupround (persistence_object_identifier)");
		$this->addSql("ALTER TABLE achimfritz_championship_competition_domain_model_crossgro_ce83d ADD CONSTRAINT FK_D30E4A213CC82627 FOREIGN KEY (guestgroupround) REFERENCES achimfritz_championship_competition_domain_model_groupround (persistence_object_identifier)");
		$this->addSql("DROP INDEX flow_identity_achimfritz_championship_competition_domain__fd683 ON achimfritz_championship_competition_domain_model_cup");
		$this->addSql("CREATE UNIQUE INDEX flow_identity_achimfritz_championship_domain_model_cup ON achimfritz_championship_competition_domain_model_cup (name)");
		$this->addSql("ALTER TABLE achimfritz_championship_competition_domain_model_cup_teams_join DROP FOREIGN KEY FK_7058D3932F8B70EC");
		$this->addSql("ALTER TABLE achimfritz_championship_competition_domain_model_cup_teams_join DROP FOREIGN KEY FK_7058D393CAA3380D");
		$this->addSql("DROP INDEX idx_7058d3932f8b70ec ON achimfritz_championship_competition_domain_model_cup_teams_join");
		$this->addSql("CREATE INDEX IDX_ACECFD7150BBF17 ON achimfritz_championship_competition_domain_model_cup_teams_join (competition_cup)");
		$this->addSql("DROP INDEX idx_7058d393caa3380d ON achimfritz_championship_competition_domain_model_cup_teams_join");
		$this->addSql("CREATE INDEX IDX_ACECFD71E0E69356 ON achimfritz_championship_competition_domain_model_cup_teams_join (competition_team)");
		$this->addSql("ALTER TABLE achimfritz_championship_competition_domain_model_cup_teams_join ADD CONSTRAINT FK_7058D3932F8B70EC FOREIGN KEY (competition_cup) REFERENCES achimfritz_championship_competition_domain_model_cup (persistence_object_identifier)");
		$this->addSql("ALTER TABLE achimfritz_championship_competition_domain_model_cup_teams_join ADD CONSTRAINT FK_7058D393CAA3380D FOREIGN KEY (competition_team) REFERENCES achimfritz_championship_competition_domain_model_team (persistence_object_identifier)");
		$this->addSql("ALTER TABLE achimfritz_championship_competition_domain_model_grouptablerow DROP FOREIGN KEY FK_65AA4911C4E0A61F");
		$this->addSql("ALTER TABLE achimfritz_championship_competition_domain_model_grouptablerow DROP FOREIGN KEY FK_65AA4911B191C15F");
		$this->addSql("DROP INDEX idx_65aa4911c4e0a61f ON achimfritz_championship_competition_domain_model_grouptablerow");
		$this->addSql("CREATE INDEX IDX_789643FC4E0A61F ON achimfritz_championship_competition_domain_model_grouptablerow (team)");
		$this->addSql("DROP INDEX idx_65aa4911b191c15f ON achimfritz_championship_competition_domain_model_grouptablerow");
		$this->addSql("CREATE INDEX IDX_789643FB191C15F ON achimfritz_championship_competition_domain_model_grouptablerow (groupround)");
		$this->addSql("ALTER TABLE achimfritz_championship_competition_domain_model_grouptablerow ADD CONSTRAINT FK_65AA4911C4E0A61F FOREIGN KEY (team) REFERENCES achimfritz_championship_competition_domain_model_team (persistence_object_identifier)");
		$this->addSql("ALTER TABLE achimfritz_championship_competition_domain_model_grouptablerow ADD CONSTRAINT FK_65AA4911B191C15F FOREIGN KEY (groupround) REFERENCES achimfritz_championship_competition_domain_model_groupround (persistence_object_identifier)");
		$this->addSql("ALTER TABLE achimfritz_championship_competition_domain_model_match DROP FOREIGN KEY FK_89981B4D7F921808");
		$this->addSql("ALTER TABLE achimfritz_championship_competition_domain_model_match DROP FOREIGN KEY FK_89981B4D87754416");
		$this->addSql("ALTER TABLE achimfritz_championship_competition_domain_model_match DROP FOREIGN KEY FK_89981B4DB79D50E4");
		$this->addSql("ALTER TABLE achimfritz_championship_competition_domain_model_match DROP FOREIGN KEY FK_89981B4DC5EEEA34");
		$this->addSql("ALTER TABLE achimfritz_championship_competition_domain_model_match DROP FOREIGN KEY FK_89981B4D136AC113");
		$this->addSql("DROP INDEX uniq_89981b4d136ac113 ON achimfritz_championship_competition_domain_model_match");
		$this->addSql("CREATE UNIQUE INDEX UNIQ_285420DC136AC113 ON achimfritz_championship_competition_domain_model_match (result)");
		$this->addSql("DROP INDEX idx_89981b4d7f921808 ON achimfritz_championship_competition_domain_model_match");
		$this->addSql("CREATE INDEX IDX_285420DC7F921808 ON achimfritz_championship_competition_domain_model_match (hostteam)");
		$this->addSql("DROP INDEX idx_89981b4d87754416 ON achimfritz_championship_competition_domain_model_match");
		$this->addSql("CREATE INDEX IDX_285420DC87754416 ON achimfritz_championship_competition_domain_model_match (guestteam)");
		$this->addSql("DROP INDEX idx_89981b4db79d50e4 ON achimfritz_championship_competition_domain_model_match");
		$this->addSql("CREATE INDEX IDX_285420DCB79D50E4 ON achimfritz_championship_competition_domain_model_match (cup)");
		$this->addSql("DROP INDEX idx_89981b4dc5eeea34 ON achimfritz_championship_competition_domain_model_match");
		$this->addSql("CREATE INDEX IDX_285420DCC5EEEA34 ON achimfritz_championship_competition_domain_model_match (round)");
		$this->addSql("ALTER TABLE achimfritz_championship_competition_domain_model_match ADD CONSTRAINT FK_89981B4D7F921808 FOREIGN KEY (hostteam) REFERENCES achimfritz_championship_competition_domain_model_team (persistence_object_identifier)");
		$this->addSql("ALTER TABLE achimfritz_championship_competition_domain_model_match ADD CONSTRAINT FK_89981B4D87754416 FOREIGN KEY (guestteam) REFERENCES achimfritz_championship_competition_domain_model_team (persistence_object_identifier)");
		$this->addSql("ALTER TABLE achimfritz_championship_competition_domain_model_match ADD CONSTRAINT FK_89981B4DB79D50E4 FOREIGN KEY (cup) REFERENCES achimfritz_championship_competition_domain_model_cup (persistence_object_identifier)");
		$this->addSql("ALTER TABLE achimfritz_championship_competition_domain_model_match ADD CONSTRAINT FK_89981B4DC5EEEA34 FOREIGN KEY (round) REFERENCES achimfritz_championship_competition_domain_model_round (persistence_object_identifier)");
		$this->addSql("ALTER TABLE achimfritz_championship_competition_domain_model_match ADD CONSTRAINT FK_89981B4D136AC113 FOREIGN KEY (result) REFERENCES achimfritz_championship_competition_domain_model_result (persistence_object_identifier)");
		$this->addSql("ALTER TABLE achimfritz_championship_competition_domain_model_round DROP FOREIGN KEY FK_362D347CB79D50E4");
		$this->addSql("DROP INDEX idx_362d347cb79d50e4 ON achimfritz_championship_competition_domain_model_round");
		$this->addSql("CREATE INDEX IDX_97E10FEDB79D50E4 ON achimfritz_championship_competition_domain_model_round (cup)");
		$this->addSql("ALTER TABLE achimfritz_championship_competition_domain_model_round ADD CONSTRAINT FK_362D347CB79D50E4 FOREIGN KEY (cup) REFERENCES achimfritz_championship_competition_domain_model_cup (persistence_object_identifier)");
		$this->addSql("DROP INDEX flow_identity_achimfritz_championship_competition_domain__419a2 ON achimfritz_championship_competition_domain_model_team");
		$this->addSql("CREATE UNIQUE INDEX flow_identity_achimfritz_championship_domain_model_team ON achimfritz_championship_competition_domain_model_team (name)");
		$this->addSql("ALTER TABLE achimfritz_championship_competition_domain_model_teamsoft_a6728 DROP FOREIGN KEY FK_F9A68DAEF933327C");
		$this->addSql("ALTER TABLE achimfritz_championship_competition_domain_model_teamsoft_a6728 DROP FOREIGN KEY FK_F9A68DAE3C4E843");
		$this->addSql("DROP INDEX idx_f9a68daef933327c ON achimfritz_championship_competition_domain_model_teamsoft_a6728");
		$this->addSql("CREATE INDEX IDX_7BB97C90F933327C ON achimfritz_championship_competition_domain_model_teamsoft_a6728 (hostmatch)");
		$this->addSql("DROP INDEX idx_f9a68dae3c4e843 ON achimfritz_championship_competition_domain_model_teamsoft_a6728");
		$this->addSql("CREATE INDEX IDX_7BB97C903C4E843 ON achimfritz_championship_competition_domain_model_teamsoft_a6728 (guestmatch)");
		$this->addSql("ALTER TABLE achimfritz_championship_competition_domain_model_teamsoft_a6728 ADD CONSTRAINT FK_F9A68DAEF933327C FOREIGN KEY (hostmatch) REFERENCES achimfritz_championship_competition_domain_model_komatch (persistence_object_identifier)");
		$this->addSql("ALTER TABLE achimfritz_championship_competition_domain_model_teamsoft_a6728 ADD CONSTRAINT FK_F9A68DAE3C4E843 FOREIGN KEY (guestmatch) REFERENCES achimfritz_championship_competition_domain_model_komatch (persistence_object_identifier)");
	}
}