<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130731212605 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
			// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_teamsoftwomatchesmatch ADD hostmatchiswinner TINYINT(1) NOT NULL, ADD guestmatchiswinner TINYINT(1) NOT NULL");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_crossgrouproundmatch DROP FOREIGN KEY FK_415239FA5616BC5D");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_crossgrouproundmatch DROP FOREIGN KEY FK_415239FA89EA8AA8");
		$this->addSql("DROP INDEX IDX_415239FA89EA8AA8 ON achimfritz_championship_domain_model_crossgrouproundmatch");
		$this->addSql("DROP INDEX IDX_415239FA5616BC5D ON achimfritz_championship_domain_model_crossgrouproundmatch");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_crossgrouproundmatch ADD hostgroupround VARCHAR(40) DEFAULT NULL, ADD guestgroupround VARCHAR(40) DEFAULT NULL, DROP semiwinnerofgroupround, DROP winnerofgroupround");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_crossgrouproundmatch ADD CONSTRAINT FK_415239FA8883CEF FOREIGN KEY (hostgroupround) REFERENCES achimfritz_championship_domain_model_groupround (persistence_object_identifier)");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_crossgrouproundmatch ADD CONSTRAINT FK_415239FA3CC82627 FOREIGN KEY (guestgroupround) REFERENCES achimfritz_championship_domain_model_groupround (persistence_object_identifier)");
		$this->addSql("CREATE INDEX IDX_415239FA8883CEF ON achimfritz_championship_domain_model_crossgrouproundmatch (hostgroupround)");
		$this->addSql("CREATE INDEX IDX_415239FA3CC82627 ON achimfritz_championship_domain_model_crossgrouproundmatch (guestgroupround)");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
			// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_crossgrouproundmatch DROP FOREIGN KEY FK_415239FA8883CEF");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_crossgrouproundmatch DROP FOREIGN KEY FK_415239FA3CC82627");
		$this->addSql("DROP INDEX IDX_415239FA8883CEF ON achimfritz_championship_domain_model_crossgrouproundmatch");
		$this->addSql("DROP INDEX IDX_415239FA3CC82627 ON achimfritz_championship_domain_model_crossgrouproundmatch");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_crossgrouproundmatch ADD semiwinnerofgroupround VARCHAR(40) DEFAULT NULL, ADD winnerofgroupround VARCHAR(40) DEFAULT NULL, DROP hostgroupround, DROP guestgroupround");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_crossgrouproundmatch ADD CONSTRAINT FK_415239FA5616BC5D FOREIGN KEY (semiwinnerofgroupround) REFERENCES achimfritz_championship_domain_model_groupround (persistence_object_identifier)");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_crossgrouproundmatch ADD CONSTRAINT FK_415239FA89EA8AA8 FOREIGN KEY (winnerofgroupround) REFERENCES achimfritz_championship_domain_model_groupround (persistence_object_identifier)");
		$this->addSql("CREATE INDEX IDX_415239FA89EA8AA8 ON achimfritz_championship_domain_model_crossgrouproundmatch (winnerofgroupround)");
		$this->addSql("CREATE INDEX IDX_415239FA5616BC5D ON achimfritz_championship_domain_model_crossgrouproundmatch (semiwinnerofgroupround)");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_teamsoftwomatchesmatch DROP hostmatchiswinner, DROP guestmatchiswinner");
	}
}

?>