<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130601103353 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
			// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_grouptablerow DROP FOREIGN KEY FK_789643FC5EEEA34");
		$this->addSql("DROP INDEX IDX_789643FC5EEEA34 ON achimfritz_championship_domain_model_grouptablerow");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_grouptablerow CHANGE round groupround VARCHAR(40) DEFAULT NULL");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_grouptablerow ADD CONSTRAINT FK_789643FB191C15F FOREIGN KEY (groupround) REFERENCES achimfritz_championship_domain_model_groupround (persistence_object_identifier)");
		$this->addSql("CREATE INDEX IDX_789643FB191C15F ON achimfritz_championship_domain_model_grouptablerow (groupround)");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
			// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_grouptablerow DROP FOREIGN KEY FK_789643FB191C15F");
		$this->addSql("DROP INDEX IDX_789643FB191C15F ON achimfritz_championship_domain_model_grouptablerow");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_grouptablerow CHANGE groupround round VARCHAR(40) DEFAULT NULL");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_grouptablerow ADD CONSTRAINT FK_789643FC5EEEA34 FOREIGN KEY (round) REFERENCES achimfritz_championship_domain_model_round (persistence_object_identifier)");
		$this->addSql("CREATE INDEX IDX_789643FC5EEEA34 ON achimfritz_championship_domain_model_grouptablerow (round)");
	}
}

?>