<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130925181045 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
			// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("CREATE TABLE achimfritz_championship_domain_model_tipgroup (persistence_object_identifier VARCHAR(40) NOT NULL, name VARCHAR(255) NOT NULL, UNIQUE INDEX flow_identity_achimfritz_championship_domain_model_tipgroup (name), PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("CREATE TABLE achimfritz_championship_domain_model_tipgroup_users_join (championship_tipgroup VARCHAR(40) NOT NULL, championship_user VARCHAR(40) NOT NULL, INDEX IDX_792ABBA5D3384B7 (championship_tipgroup), INDEX IDX_792ABBAA995E300 (championship_user), PRIMARY KEY(championship_tipgroup, championship_user)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_tipgroup_users_join ADD CONSTRAINT FK_792ABBA5D3384B7 FOREIGN KEY (championship_tipgroup) REFERENCES achimfritz_championship_domain_model_tipgroup (persistence_object_identifier)");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_tipgroup_users_join ADD CONSTRAINT FK_792ABBAA995E300 FOREIGN KEY (championship_user) REFERENCES achimfritz_championship_domain_model_user (persistence_object_identifier)");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_user ADD maintipgroup VARCHAR(40) DEFAULT NULL");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_user ADD CONSTRAINT FK_EA9439FA73D5BFB8 FOREIGN KEY (maintipgroup) REFERENCES achimfritz_championship_domain_model_tipgroup (persistence_object_identifier)");
		$this->addSql("CREATE INDEX IDX_EA9439FA73D5BFB8 ON achimfritz_championship_domain_model_user (maintipgroup)");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
			// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_tipgroup_users_join DROP FOREIGN KEY FK_792ABBA5D3384B7");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_user DROP FOREIGN KEY FK_EA9439FA73D5BFB8");
		$this->addSql("DROP TABLE achimfritz_championship_domain_model_tipgroup");
		$this->addSql("DROP TABLE achimfritz_championship_domain_model_tipgroup_users_join");
		$this->addSql("DROP INDEX IDX_EA9439FA73D5BFB8 ON achimfritz_championship_domain_model_user");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_user DROP maintipgroup");
	}
}

?>
