<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130526140912 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
			// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_points ADD generalmatch VARCHAR(40) DEFAULT NULL");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_points ADD CONSTRAINT FK_D8E7EBBCDFBDA53F FOREIGN KEY (generalmatch) REFERENCES achimfritz_championship_domain_model_match (persistence_object_identifier)");
		$this->addSql("CREATE INDEX IDX_D8E7EBBCDFBDA53F ON achimfritz_championship_domain_model_points (generalmatch)");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_tip ADD generalmatch VARCHAR(40) DEFAULT NULL");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_tip ADD CONSTRAINT FK_9226C7D7DFBDA53F FOREIGN KEY (generalmatch) REFERENCES achimfritz_championship_domain_model_match (persistence_object_identifier)");
		$this->addSql("CREATE INDEX IDX_9226C7D7DFBDA53F ON achimfritz_championship_domain_model_tip (generalmatch)");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
			// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_points DROP FOREIGN KEY FK_D8E7EBBCDFBDA53F");
		$this->addSql("DROP INDEX IDX_D8E7EBBCDFBDA53F ON achimfritz_championship_domain_model_points");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_points DROP generalmatch");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_tip DROP FOREIGN KEY FK_9226C7D7DFBDA53F");
		$this->addSql("DROP INDEX IDX_9226C7D7DFBDA53F ON achimfritz_championship_domain_model_tip");
		$this->addSql("ALTER TABLE achimfritz_championship_domain_model_tip DROP generalmatch");
	}
}

?>