-
  name: 'Redirect to Standard View'
  uriPattern: ''
  defaults:
    '@package':    'AchimFritz.ChampionShip'
    '@controller': 'Standard'
    '@action':     'index'
    '@format':     'html'

-
  name: 'default with action and format'
  uriPattern: '{@package}/{@subpackage}/{@controller}/{@action}(.{@format})'
  defaults:
    '@format':     'html'
  appendExceedingArguments: true
