-
  name: 'Redirect to Standard View'
  uriPattern: ''
  defaults:
    '@package':    'AchimFritz.ChampionShip'
    '@controller': 'Standard'
    '@action':     'index'
    '@format':     'html'

  
#-
#  name: 'finalmatch'
#  uriPattern: '{@package}/match/finalmatch(/{@action})'
#  defaults:
#    '@controller': 'Match\FinalMatch'
    
#-
#  name: 'quarter final match'
#  uriPattern: '{@package}/match/@controller(/{@action})'
#  defaults:
#    '@controller': 'Match\@controller'
#  appendExceedingArguments: true
