TYPO3:
  Flow:
    security:
      authentication:
        #authenticationStrategy: atLeastOneToken
        providers:
          DefaultProvider:
            provider: PersistedUsernamePasswordProvider
            #entryPoint: 'WebRedirect'
            token: TYPO3\Flow\Security\Authentication\Token\UsernamePasswordHttpBasic
            #entryPointOptions:
            #  routeValues:
            #    '@package': 'AchimFritz.Championship'
            #    '@controller': 'Standard'
            #    '@action': 'index'
    i18n:
      defaultLocale: de
    #persistence:
    #  doctrine:
    #    sqlLogger: TYPO3\Flow\Persistence\Doctrine\Logging\SqlLogger
