TYPO3:
  Flow:
    security:
      authentication:
        authenticationStrategy: oneToken
        providers:
          DefaultProvider:
            provider: PersistedUsernamePasswordProvider
            entryPoint: 'WebRedirect'
            entryPointOptions:
              routeValues:
                '@package': 'AchimFritz.Championship'
                '@controller': 'Standard'
                '@action': 'index'
    i18n:
      defaultLocale: de
    #persistence:
    #  doctrine:
    #    sqlLogger: TYPO3\Flow\Persistence\Doctrine\Logging\SqlLogger
