AchimFritz:
  ChampionShip:
    csStyle: 1
TYPO3:
  Flow:
    security:
      authentication:
        #authenticationStrategy: atLeastOneToken
        providers:
          ApiProvider:
            provider: PersistedUsernamePasswordProvider
            token: TYPO3\Flow\Security\Authentication\Token\UsernamePasswordHttpBasic
          DefaultProvider:
            provider: PersistedUsernamePasswordProvider
            entryPoint: 'WebRedirect'
            token: TYPO3\Flow\Security\Authentication\Token\UsernamePassword
            entryPointOptions:
              routeValues:
                '@package': 'AchimFritz.Championship'
                '@controller': 'Standard'
                '@action': 'index'
    i18n:
      defaultLocale: de
    #persistence:
    #  doctrine:
    #    sqlLogger: TYPO3\Flow\Persistence\Doctrine\Logging\SqlLogger
